// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/memberclass-backend-golang/internal/domain/dto/request/comments"
	dto "github.com/memberclass-backend-golang/internal/domain/dto/response/comment"
	mock "github.com/stretchr/testify/mock"
)

// MockCommentUseCase is an autogenerated mock type for the CommentUseCase type
type MockCommentUseCase struct {
	mock.Mock
}

type MockCommentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentUseCase) EXPECT() *MockCommentUseCase_Expecter {
	return &MockCommentUseCase_Expecter{mock: &_m.Mock}
}

// GetComments provides a mock function with given fields: ctx, tenantID, req
func (_m *MockCommentUseCase) GetComments(ctx context.Context, tenantID string, req *comments.GetCommentsRequest) (*dto.CommentsPaginationResponse, error) {
	ret := _m.Called(ctx, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 *dto.CommentsPaginationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *comments.GetCommentsRequest) (*dto.CommentsPaginationResponse, error)); ok {
		return rf(ctx, tenantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *comments.GetCommentsRequest) *dto.CommentsPaginationResponse); ok {
		r0 = rf(ctx, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CommentsPaginationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *comments.GetCommentsRequest) error); ok {
		r1 = rf(ctx, tenantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUseCase_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockCommentUseCase_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - req *request.GetCommentsRequest
func (_e *MockCommentUseCase_Expecter) GetComments(ctx interface{}, tenantID interface{}, req interface{}) *MockCommentUseCase_GetComments_Call {
	return &MockCommentUseCase_GetComments_Call{Call: _e.mock.On("GetComments", ctx, tenantID, req)}
}

func (_c *MockCommentUseCase_GetComments_Call) Run(run func(ctx context.Context, tenantID string, req *comments.GetCommentsRequest)) *MockCommentUseCase_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*comments.GetCommentsRequest))
	})
	return _c
}

func (_c *MockCommentUseCase_GetComments_Call) Return(_a0 *dto.CommentsPaginationResponse, _a1 error) *MockCommentUseCase_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUseCase_GetComments_Call) RunAndReturn(run func(context.Context, string, *comments.GetCommentsRequest) (*dto.CommentsPaginationResponse, error)) *MockCommentUseCase_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAnswer provides a mock function with given fields: ctx, commentID, tenantID, req
func (_m *MockCommentUseCase) UpdateAnswer(ctx context.Context, commentID string, tenantID string, req comments.UpdateCommentRequest) (*dto.CommentResponse, error) {
	ret := _m.Called(ctx, commentID, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAnswer")
	}

	var r0 *dto.CommentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, comments.UpdateCommentRequest) (*dto.CommentResponse, error)); ok {
		return rf(ctx, commentID, tenantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, comments.UpdateCommentRequest) *dto.CommentResponse); ok {
		r0 = rf(ctx, commentID, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CommentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, comments.UpdateCommentRequest) error); ok {
		r1 = rf(ctx, commentID, tenantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentUseCase_UpdateAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAnswer'
type MockCommentUseCase_UpdateAnswer_Call struct {
	*mock.Call
}

// UpdateAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - tenantID string
//   - req request.UpdateCommentRequest
func (_e *MockCommentUseCase_Expecter) UpdateAnswer(ctx interface{}, commentID interface{}, tenantID interface{}, req interface{}) *MockCommentUseCase_UpdateAnswer_Call {
	return &MockCommentUseCase_UpdateAnswer_Call{Call: _e.mock.On("UpdateAnswer", ctx, commentID, tenantID, req)}
}

func (_c *MockCommentUseCase_UpdateAnswer_Call) Run(run func(ctx context.Context, commentID string, tenantID string, req comments.UpdateCommentRequest)) *MockCommentUseCase_UpdateAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(comments.UpdateCommentRequest))
	})
	return _c
}

func (_c *MockCommentUseCase_UpdateAnswer_Call) Return(_a0 *dto.CommentResponse, _a1 error) *MockCommentUseCase_UpdateAnswer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentUseCase_UpdateAnswer_Call) RunAndReturn(run func(context.Context, string, string, comments.UpdateCommentRequest) (*dto.CommentResponse, error)) *MockCommentUseCase_UpdateAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentUseCase creates a new instance of MockCommentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentUseCase {
	mock := &MockCommentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
