// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request/auth"
	response "github.com/memberclass-backend-golang/internal/domain/dto/response/auth"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthUseCase is an autogenerated mock type for the AuthUseCase type
type MockAuthUseCase struct {
	mock.Mock
}

type MockAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCase) EXPECT() *MockAuthUseCase_Expecter {
	return &MockAuthUseCase_Expecter{mock: &_m.Mock}
}

// GenerateMagicLink provides a mock function with given fields: ctx, req, tenantID
func (_m *MockAuthUseCase) GenerateMagicLink(ctx context.Context, req request.AuthRequest, tenantID string) (*response.AuthResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateMagicLink")
	}

	var r0 *response.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.AuthRequest, string) (*response.AuthResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.AuthRequest, string) *response.AuthResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.AuthRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_GenerateMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateMagicLink'
type MockAuthUseCase_GenerateMagicLink_Call struct {
	*mock.Call
}

// GenerateMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.AuthRequest
//   - tenantID string
func (_e *MockAuthUseCase_Expecter) GenerateMagicLink(ctx interface{}, req interface{}, tenantID interface{}) *MockAuthUseCase_GenerateMagicLink_Call {
	return &MockAuthUseCase_GenerateMagicLink_Call{Call: _e.mock.On("GenerateMagicLink", ctx, req, tenantID)}
}

func (_c *MockAuthUseCase_GenerateMagicLink_Call) Run(run func(ctx context.Context, req request.AuthRequest, tenantID string)) *MockAuthUseCase_GenerateMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.AuthRequest), args[2].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_GenerateMagicLink_Call) Return(_a0 *response.AuthResponse, _a1 error) *MockAuthUseCase_GenerateMagicLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_GenerateMagicLink_Call) RunAndReturn(run func(context.Context, request.AuthRequest, string) (*response.AuthResponse, error)) *MockAuthUseCase_GenerateMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUseCase creates a new instance of MockAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCase {
	mock := &MockAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
