// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	responsestudent "github.com/memberclass-backend-golang/internal/domain/dto/response/student"

	student "github.com/memberclass-backend-golang/internal/domain/dto/request/student"
)

// MockStudentReportUseCase is an autogenerated mock type for the StudentReportUseCase type
type MockStudentReportUseCase struct {
	mock.Mock
}

type MockStudentReportUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentReportUseCase) EXPECT() *MockStudentReportUseCase_Expecter {
	return &MockStudentReportUseCase_Expecter{mock: &_m.Mock}
}

// GetStudentReport provides a mock function with given fields: ctx, req, tenantID
func (_m *MockStudentReportUseCase) GetStudentReport(ctx context.Context, req student.GetStudentReportRequest, tenantID string) (*responsestudent.StudentReportResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentReport")
	}

	var r0 *responsestudent.StudentReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, student.GetStudentReportRequest, string) (*responsestudent.StudentReportResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, student.GetStudentReportRequest, string) *responsestudent.StudentReportResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responsestudent.StudentReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, student.GetStudentReportRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentReportUseCase_GetStudentReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentReport'
type MockStudentReportUseCase_GetStudentReport_Call struct {
	*mock.Call
}

// GetStudentReport is a helper method to define mock.On call
//   - ctx context.Context
//   - req student.GetStudentReportRequest
//   - tenantID string
func (_e *MockStudentReportUseCase_Expecter) GetStudentReport(ctx interface{}, req interface{}, tenantID interface{}) *MockStudentReportUseCase_GetStudentReport_Call {
	return &MockStudentReportUseCase_GetStudentReport_Call{Call: _e.mock.On("GetStudentReport", ctx, req, tenantID)}
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) Run(run func(ctx context.Context, req student.GetStudentReportRequest, tenantID string)) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(student.GetStudentReportRequest), args[2].(string))
	})
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) Return(_a0 *responsestudent.StudentReportResponse, _a1 error) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) RunAndReturn(run func(context.Context, student.GetStudentReportRequest, string) (*responsestudent.StudentReportResponse, error)) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetStudentsRanking provides a mock function with given fields: ctx, req, tenantID
func (_m *MockStudentReportUseCase) GetStudentsRanking(ctx context.Context, req student.GetStudentsRankingRequest, tenantID string) (*responsestudent.StudentsRankingResponse, bool, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentsRanking")
	}

	var r0 *responsestudent.StudentsRankingResponse
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, student.GetStudentsRankingRequest, string) (*responsestudent.StudentsRankingResponse, bool, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, student.GetStudentsRankingRequest, string) *responsestudent.StudentsRankingResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responsestudent.StudentsRankingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, student.GetStudentsRankingRequest, string) bool); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, student.GetStudentsRankingRequest, string) error); ok {
		r2 = rf(ctx, req, tenantID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStudentReportUseCase_GetStudentsRanking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentsRanking'
type MockStudentReportUseCase_GetStudentsRanking_Call struct {
	*mock.Call
}

// GetStudentsRanking is a helper method to define mock.On call
//   - ctx context.Context
//   - req student.GetStudentsRankingRequest
//   - tenantID string
func (_e *MockStudentReportUseCase_Expecter) GetStudentsRanking(ctx interface{}, req interface{}, tenantID interface{}) *MockStudentReportUseCase_GetStudentsRanking_Call {
	return &MockStudentReportUseCase_GetStudentsRanking_Call{Call: _e.mock.On("GetStudentsRanking", ctx, req, tenantID)}
}

func (_c *MockStudentReportUseCase_GetStudentsRanking_Call) Run(run func(ctx context.Context, req student.GetStudentsRankingRequest, tenantID string)) *MockStudentReportUseCase_GetStudentsRanking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(student.GetStudentsRankingRequest), args[2].(string))
	})
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentsRanking_Call) Return(_a0 *responsestudent.StudentsRankingResponse, _a1 bool, _a2 error) *MockStudentReportUseCase_GetStudentsRanking_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentsRanking_Call) RunAndReturn(run func(context.Context, student.GetStudentsRankingRequest, string) (*responsestudent.StudentsRankingResponse, bool, error)) *MockStudentReportUseCase_GetStudentsRanking_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentReportUseCase creates a new instance of MockStudentReportUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentReportUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentReportUseCase {
	mock := &MockStudentReportUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
