// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockUserPurchaseUseCase is an autogenerated mock type for the UserPurchaseUseCase type
type MockUserPurchaseUseCase struct {
	mock.Mock
}

type MockUserPurchaseUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserPurchaseUseCase) EXPECT() *MockUserPurchaseUseCase_Expecter {
	return &MockUserPurchaseUseCase_Expecter{mock: &_m.Mock}
}

// GetUserPurchases provides a mock function with given fields: ctx, req, tenantID
func (_m *MockUserPurchaseUseCase) GetUserPurchases(ctx context.Context, req request.GetUserPurchasesRequest, tenantID string) (*response.UserPurchasesResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPurchases")
	}

	var r0 *response.UserPurchasesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetUserPurchasesRequest, string) (*response.UserPurchasesResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetUserPurchasesRequest, string) *response.UserPurchasesResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserPurchasesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetUserPurchasesRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserPurchaseUseCase_GetUserPurchases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPurchases'
type MockUserPurchaseUseCase_GetUserPurchases_Call struct {
	*mock.Call
}

// GetUserPurchases is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.GetUserPurchasesRequest
//   - tenantID string
func (_e *MockUserPurchaseUseCase_Expecter) GetUserPurchases(ctx interface{}, req interface{}, tenantID interface{}) *MockUserPurchaseUseCase_GetUserPurchases_Call {
	return &MockUserPurchaseUseCase_GetUserPurchases_Call{Call: _e.mock.On("GetUserPurchases", ctx, req, tenantID)}
}

func (_c *MockUserPurchaseUseCase_GetUserPurchases_Call) Run(run func(ctx context.Context, req request.GetUserPurchasesRequest, tenantID string)) *MockUserPurchaseUseCase_GetUserPurchases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.GetUserPurchasesRequest), args[2].(string))
	})
	return _c
}

func (_c *MockUserPurchaseUseCase_GetUserPurchases_Call) Return(_a0 *response.UserPurchasesResponse, _a1 error) *MockUserPurchaseUseCase_GetUserPurchases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserPurchaseUseCase_GetUserPurchases_Call) RunAndReturn(run func(context.Context, request.GetUserPurchasesRequest, string) (*response.UserPurchasesResponse, error)) *MockUserPurchaseUseCase_GetUserPurchases_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserPurchaseUseCase creates a new instance of MockUserPurchaseUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserPurchaseUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserPurchaseUseCase {
	mock := &MockUserPurchaseUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
