// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockPostSocialUseCase is an autogenerated mock type for the PostSocialUseCase type
type MockPostSocialUseCase struct {
	mock.Mock
}

type MockPostSocialUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostSocialUseCase) EXPECT() *MockPostSocialUseCase_Expecter {
	return &MockPostSocialUseCase_Expecter{mock: &_m.Mock}
}

// CreatePostSocial provides a mock function with given fields: ctx, req, tenantID
func (_m *MockPostSocialUseCase) CreatePostSocial(ctx context.Context, req request.CreatePostSocialRequest, tenantID string) (*response.PostSocialResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePostSocial")
	}

	var r0 *response.PostSocialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.CreatePostSocialRequest, string) (*response.PostSocialResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.CreatePostSocialRequest, string) *response.PostSocialResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PostSocialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.CreatePostSocialRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostSocialUseCase_CreatePostSocial_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePostSocial'
type MockPostSocialUseCase_CreatePostSocial_Call struct {
	*mock.Call
}

// CreatePostSocial is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.CreatePostSocialRequest
//   - tenantID string
func (_e *MockPostSocialUseCase_Expecter) CreatePostSocial(ctx interface{}, req interface{}, tenantID interface{}) *MockPostSocialUseCase_CreatePostSocial_Call {
	return &MockPostSocialUseCase_CreatePostSocial_Call{Call: _e.mock.On("CreatePostSocial", ctx, req, tenantID)}
}

func (_c *MockPostSocialUseCase_CreatePostSocial_Call) Run(run func(ctx context.Context, req request.CreatePostSocialRequest, tenantID string)) *MockPostSocialUseCase_CreatePostSocial_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.CreatePostSocialRequest), args[2].(string))
	})
	return _c
}

func (_c *MockPostSocialUseCase_CreatePostSocial_Call) Return(_a0 *response.PostSocialResponse, _a1 error) *MockPostSocialUseCase_CreatePostSocial_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostSocialUseCase_CreatePostSocial_Call) RunAndReturn(run func(context.Context, request.CreatePostSocialRequest, string) (*response.PostSocialResponse, error)) *MockPostSocialUseCase_CreatePostSocial_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostSocialUseCase creates a new instance of MockPostSocialUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostSocialUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostSocialUseCase {
	mock := &MockPostSocialUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
