// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entitiesuser "github.com/memberclass-backend-golang/internal/domain/entities/user"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// BelongsToTenant provides a mock function with given fields: userID, tenantID
func (_m *MockUserRepository) BelongsToTenant(userID string, tenantID string) (bool, error) {
	ret := _m.Called(userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for BelongsToTenant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(userID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(userID, tenantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_BelongsToTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BelongsToTenant'
type MockUserRepository_BelongsToTenant_Call struct {
	*mock.Call
}

// BelongsToTenant is a helper method to define mock.On call
//   - userID string
//   - tenantID string
func (_e *MockUserRepository_Expecter) BelongsToTenant(userID interface{}, tenantID interface{}) *MockUserRepository_BelongsToTenant_Call {
	return &MockUserRepository_BelongsToTenant_Call{Call: _e.mock.On("BelongsToTenant", userID, tenantID)}
}

func (_c *MockUserRepository_BelongsToTenant_Call) Run(run func(userID string, tenantID string)) *MockUserRepository_BelongsToTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_BelongsToTenant_Call) Return(_a0 bool, _a1 error) *MockUserRepository_BelongsToTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_BelongsToTenant_Call) RunAndReturn(run func(string, string) (bool, error)) *MockUserRepository_BelongsToTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByID provides a mock function with given fields: userID
func (_m *MockUserRepository) ExistsByID(userID string) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ExistsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByID'
type MockUserRepository_ExistsByID_Call struct {
	*mock.Call
}

// ExistsByID is a helper method to define mock.On call
//   - userID string
func (_e *MockUserRepository_Expecter) ExistsByID(userID interface{}) *MockUserRepository_ExistsByID_Call {
	return &MockUserRepository_ExistsByID_Call{Call: _e.mock.On("ExistsByID", userID)}
}

func (_c *MockUserRepository_ExistsByID_Call) Run(run func(userID string)) *MockUserRepository_ExistsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_ExistsByID_Call) Return(_a0 bool, _a1 error) *MockUserRepository_ExistsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ExistsByID_Call) RunAndReturn(run func(string) (bool, error)) *MockUserRepository_ExistsByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: email
func (_m *MockUserRepository) FindByEmail(email string) (*entitiesuser.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *entitiesuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entitiesuser.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *entitiesuser.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitiesuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(_a0 *entitiesuser.User, _a1 error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(string) (*entitiesuser.User, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: userID
func (_m *MockUserRepository) FindByID(userID string) (*entitiesuser.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entitiesuser.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entitiesuser.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) *entitiesuser.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitiesuser.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - userID string
func (_e *MockUserRepository_Expecter) FindByID(userID interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", userID)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(userID string)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(_a0 *entitiesuser.User, _a1 error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(string) (*entitiesuser.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDeliveryIDs provides a mock function with given fields: ctx, userID, tenantID
func (_m *MockUserRepository) GetUserDeliveryIDs(ctx context.Context, userID string, tenantID string) ([]string, error) {
	ret := _m.Called(ctx, userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDeliveryIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return rf(ctx, userID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = rf(ctx, userID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserDeliveryIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDeliveryIDs'
type MockUserRepository_GetUserDeliveryIDs_Call struct {
	*mock.Call
}

// GetUserDeliveryIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
func (_e *MockUserRepository_Expecter) GetUserDeliveryIDs(ctx interface{}, userID interface{}, tenantID interface{}) *MockUserRepository_GetUserDeliveryIDs_Call {
	return &MockUserRepository_GetUserDeliveryIDs_Call{Call: _e.mock.On("GetUserDeliveryIDs", ctx, userID, tenantID)}
}

func (_c *MockUserRepository_GetUserDeliveryIDs_Call) Run(run func(ctx context.Context, userID string, tenantID string)) *MockUserRepository_GetUserDeliveryIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserDeliveryIDs_Call) Return(_a0 []string, _a1 error) *MockUserRepository_GetUserDeliveryIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserDeliveryIDs_Call) RunAndReturn(run func(context.Context, string, string) ([]string, error)) *MockUserRepository_GetUserDeliveryIDs_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserOwner provides a mock function with given fields: ctx, userID, tenantID
func (_m *MockUserRepository) IsUserOwner(ctx context.Context, userID string, tenantID string) (bool, error) {
	ret := _m.Called(ctx, userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, tenantID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_IsUserOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserOwner'
type MockUserRepository_IsUserOwner_Call struct {
	*mock.Call
}

// IsUserOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
func (_e *MockUserRepository_Expecter) IsUserOwner(ctx interface{}, userID interface{}, tenantID interface{}) *MockUserRepository_IsUserOwner_Call {
	return &MockUserRepository_IsUserOwner_Call{Call: _e.mock.On("IsUserOwner", ctx, userID, tenantID)}
}

func (_c *MockUserRepository_IsUserOwner_Call) Run(run func(ctx context.Context, userID string, tenantID string)) *MockUserRepository_IsUserOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_IsUserOwner_Call) Return(_a0 bool, _a1 error) *MockUserRepository_IsUserOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_IsUserOwner_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockUserRepository_IsUserOwner_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMagicToken provides a mock function with given fields: ctx, userID, tokenHash, validUntil
func (_m *MockUserRepository) UpdateMagicToken(ctx context.Context, userID string, tokenHash string, validUntil time.Time) error {
	ret := _m.Called(ctx, userID, tokenHash, validUntil)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMagicToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(ctx, userID, tokenHash, validUntil)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateMagicToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMagicToken'
type MockUserRepository_UpdateMagicToken_Call struct {
	*mock.Call
}

// UpdateMagicToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenHash string
//   - validUntil time.Time
func (_e *MockUserRepository_Expecter) UpdateMagicToken(ctx interface{}, userID interface{}, tokenHash interface{}, validUntil interface{}) *MockUserRepository_UpdateMagicToken_Call {
	return &MockUserRepository_UpdateMagicToken_Call{Call: _e.mock.On("UpdateMagicToken", ctx, userID, tokenHash, validUntil)}
}

func (_c *MockUserRepository_UpdateMagicToken_Call) Run(run func(ctx context.Context, userID string, tokenHash string, validUntil time.Time)) *MockUserRepository_UpdateMagicToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *MockUserRepository_UpdateMagicToken_Call) Return(_a0 error) *MockUserRepository_UpdateMagicToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateMagicToken_Call) RunAndReturn(run func(context.Context, string, string, time.Time) error) *MockUserRepository_UpdateMagicToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
