// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/memberclass-backend-golang/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockRateLimiterTenant is an autogenerated mock type for the RateLimiterTenant type
type MockRateLimiterTenant struct {
	mock.Mock
}

type MockRateLimiterTenant_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiterTenant) EXPECT() *MockRateLimiterTenant_Expecter {
	return &MockRateLimiterTenant_Expecter{mock: &_m.Mock}
}

// CheckLimit provides a mock function with given fields: ctx, tenantID, endpoint
func (_m *MockRateLimiterTenant) CheckLimit(ctx context.Context, tenantID string, endpoint string) (bool, ports.RateLimitInfo, error) {
	ret := _m.Called(ctx, tenantID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for CheckLimit")
	}

	var r0 bool
	var r1 ports.RateLimitInfo
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, ports.RateLimitInfo, error)); ok {
		return rf(ctx, tenantID, endpoint)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, tenantID, endpoint)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) ports.RateLimitInfo); ok {
		r1 = rf(ctx, tenantID, endpoint)
	} else {
		r1 = ret.Get(1).(ports.RateLimitInfo)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, tenantID, endpoint)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRateLimiterTenant_CheckLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLimit'
type MockRateLimiterTenant_CheckLimit_Call struct {
	*mock.Call
}

// CheckLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - endpoint string
func (_e *MockRateLimiterTenant_Expecter) CheckLimit(ctx interface{}, tenantID interface{}, endpoint interface{}) *MockRateLimiterTenant_CheckLimit_Call {
	return &MockRateLimiterTenant_CheckLimit_Call{Call: _e.mock.On("CheckLimit", ctx, tenantID, endpoint)}
}

func (_c *MockRateLimiterTenant_CheckLimit_Call) Run(run func(ctx context.Context, tenantID string, endpoint string)) *MockRateLimiterTenant_CheckLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRateLimiterTenant_CheckLimit_Call) Return(_a0 bool, _a1 ports.RateLimitInfo, _a2 error) *MockRateLimiterTenant_CheckLimit_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRateLimiterTenant_CheckLimit_Call) RunAndReturn(run func(context.Context, string, string) (bool, ports.RateLimitInfo, error)) *MockRateLimiterTenant_CheckLimit_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, tenantID, endpoint
func (_m *MockRateLimiterTenant) Increment(ctx context.Context, tenantID string, endpoint string) error {
	ret := _m.Called(ctx, tenantID, endpoint)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, endpoint)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRateLimiterTenant_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockRateLimiterTenant_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - endpoint string
func (_e *MockRateLimiterTenant_Expecter) Increment(ctx interface{}, tenantID interface{}, endpoint interface{}) *MockRateLimiterTenant_Increment_Call {
	return &MockRateLimiterTenant_Increment_Call{Call: _e.mock.On("Increment", ctx, tenantID, endpoint)}
}

func (_c *MockRateLimiterTenant_Increment_Call) Run(run func(ctx context.Context, tenantID string, endpoint string)) *MockRateLimiterTenant_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRateLimiterTenant_Increment_Call) Return(_a0 error) *MockRateLimiterTenant_Increment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRateLimiterTenant_Increment_Call) RunAndReturn(run func(context.Context, string, string) error) *MockRateLimiterTenant_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiterTenant creates a new instance of MockRateLimiterTenant. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiterTenant(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiterTenant {
	mock := &MockRateLimiterTenant{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
