// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request"
	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockAITenantUseCase is an autogenerated mock type for the AITenantUseCase type
type MockAITenantUseCase struct {
	mock.Mock
}

type MockAITenantUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAITenantUseCase) EXPECT() *MockAITenantUseCase_Expecter {
	return &MockAITenantUseCase_Expecter{mock: &_m.Mock}
}

// GetTenantsWithAIEnabled provides a mock function with given fields: ctx
func (_m *MockAITenantUseCase) GetTenantsWithAIEnabled(ctx context.Context) (*response.AITenantsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantsWithAIEnabled")
	}

	var r0 *response.AITenantsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.AITenantsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.AITenantsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.AITenantsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAITenantUseCase_GetTenantsWithAIEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantsWithAIEnabled'
type MockAITenantUseCase_GetTenantsWithAIEnabled_Call struct {
	*mock.Call
}

// GetTenantsWithAIEnabled is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAITenantUseCase_Expecter) GetTenantsWithAIEnabled(ctx interface{}) *MockAITenantUseCase_GetTenantsWithAIEnabled_Call {
	return &MockAITenantUseCase_GetTenantsWithAIEnabled_Call{Call: _e.mock.On("GetTenantsWithAIEnabled", ctx)}
}

func (_c *MockAITenantUseCase_GetTenantsWithAIEnabled_Call) Run(run func(ctx context.Context)) *MockAITenantUseCase_GetTenantsWithAIEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAITenantUseCase_GetTenantsWithAIEnabled_Call) Return(_a0 *response.AITenantsResponse, _a1 error) *MockAITenantUseCase_GetTenantsWithAIEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAITenantUseCase_GetTenantsWithAIEnabled_Call) RunAndReturn(run func(context.Context) (*response.AITenantsResponse, error)) *MockAITenantUseCase_GetTenantsWithAIEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessLessonsTenant provides a mock function with given fields: ctx, req
func (_m *MockAITenantUseCase) ProcessLessonsTenant(ctx context.Context, req request.ProcessLessonsTenantRequest) (*response.ProcessLessonsTenantResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ProcessLessonsTenant")
	}

	var r0 *response.ProcessLessonsTenantResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.ProcessLessonsTenantRequest) (*response.ProcessLessonsTenantResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.ProcessLessonsTenantRequest) *response.ProcessLessonsTenantResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ProcessLessonsTenantResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.ProcessLessonsTenantRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAITenantUseCase_ProcessLessonsTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessLessonsTenant'
type MockAITenantUseCase_ProcessLessonsTenant_Call struct {
	*mock.Call
}

// ProcessLessonsTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.ProcessLessonsTenantRequest
func (_e *MockAITenantUseCase_Expecter) ProcessLessonsTenant(ctx interface{}, req interface{}) *MockAITenantUseCase_ProcessLessonsTenant_Call {
	return &MockAITenantUseCase_ProcessLessonsTenant_Call{Call: _e.mock.On("ProcessLessonsTenant", ctx, req)}
}

func (_c *MockAITenantUseCase_ProcessLessonsTenant_Call) Run(run func(ctx context.Context, req request.ProcessLessonsTenantRequest)) *MockAITenantUseCase_ProcessLessonsTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.ProcessLessonsTenantRequest))
	})
	return _c
}

func (_c *MockAITenantUseCase_ProcessLessonsTenant_Call) Return(_a0 *response.ProcessLessonsTenantResponse, _a1 error) *MockAITenantUseCase_ProcessLessonsTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAITenantUseCase_ProcessLessonsTenant_Call) RunAndReturn(run func(context.Context, request.ProcessLessonsTenantRequest) (*response.ProcessLessonsTenantResponse, error)) *MockAITenantUseCase_ProcessLessonsTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAITenantUseCase creates a new instance of MockAITenantUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAITenantUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAITenantUseCase {
	mock := &MockAITenantUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
