// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	responseuser "github.com/memberclass-backend-golang/internal/domain/dto/response/user"

	user "github.com/memberclass-backend-golang/internal/domain/dto/request/user"
)

// MockActivitySummaryUseCase is an autogenerated mock type for the ActivitySummaryUseCase type
type MockActivitySummaryUseCase struct {
	mock.Mock
}

type MockActivitySummaryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivitySummaryUseCase) EXPECT() *MockActivitySummaryUseCase_Expecter {
	return &MockActivitySummaryUseCase_Expecter{mock: &_m.Mock}
}

// GetActivitySummary provides a mock function with given fields: ctx, req, tenantID
func (_m *MockActivitySummaryUseCase) GetActivitySummary(ctx context.Context, req user.GetActivitySummaryRequest, tenantID string) (*responseuser.ActivitySummaryResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetActivitySummary")
	}

	var r0 *responseuser.ActivitySummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.GetActivitySummaryRequest, string) (*responseuser.ActivitySummaryResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.GetActivitySummaryRequest, string) *responseuser.ActivitySummaryResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responseuser.ActivitySummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.GetActivitySummaryRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockActivitySummaryUseCase_GetActivitySummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivitySummary'
type MockActivitySummaryUseCase_GetActivitySummary_Call struct {
	*mock.Call
}

// GetActivitySummary is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.GetActivitySummaryRequest
//   - tenantID string
func (_e *MockActivitySummaryUseCase_Expecter) GetActivitySummary(ctx interface{}, req interface{}, tenantID interface{}) *MockActivitySummaryUseCase_GetActivitySummary_Call {
	return &MockActivitySummaryUseCase_GetActivitySummary_Call{Call: _e.mock.On("GetActivitySummary", ctx, req, tenantID)}
}

func (_c *MockActivitySummaryUseCase_GetActivitySummary_Call) Run(run func(ctx context.Context, req user.GetActivitySummaryRequest, tenantID string)) *MockActivitySummaryUseCase_GetActivitySummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.GetActivitySummaryRequest), args[2].(string))
	})
	return _c
}

func (_c *MockActivitySummaryUseCase_GetActivitySummary_Call) Return(_a0 *responseuser.ActivitySummaryResponse, _a1 error) *MockActivitySummaryUseCase_GetActivitySummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockActivitySummaryUseCase_GetActivitySummary_Call) RunAndReturn(run func(context.Context, user.GetActivitySummaryRequest, string) (*responseuser.ActivitySummaryResponse, error)) *MockActivitySummaryUseCase_GetActivitySummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockActivitySummaryUseCase creates a new instance of MockActivitySummaryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivitySummaryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivitySummaryUseCase {
	mock := &MockActivitySummaryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
