// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	activity "github.com/memberclass-backend-golang/internal/domain/dto/response/user/activity"

	mock "github.com/stretchr/testify/mock"

	user "github.com/memberclass-backend-golang/internal/domain/dto/request/user"
)

// MockUserActivityUseCase is an autogenerated mock type for the UserActivityUseCase type
type MockUserActivityUseCase struct {
	mock.Mock
}

type MockUserActivityUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserActivityUseCase) EXPECT() *MockUserActivityUseCase_Expecter {
	return &MockUserActivityUseCase_Expecter{mock: &_m.Mock}
}

// GetUserActivities provides a mock function with given fields: ctx, req, tenantID
func (_m *MockUserActivityUseCase) GetUserActivities(ctx context.Context, req user.GetActivitiesRequest, tenantID string) (*activity.ActivityResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserActivities")
	}

	var r0 *activity.ActivityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.GetActivitiesRequest, string) (*activity.ActivityResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.GetActivitiesRequest, string) *activity.ActivityResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*activity.ActivityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.GetActivitiesRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserActivityUseCase_GetUserActivities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserActivities'
type MockUserActivityUseCase_GetUserActivities_Call struct {
	*mock.Call
}

// GetUserActivities is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.GetActivitiesRequest
//   - tenantID string
func (_e *MockUserActivityUseCase_Expecter) GetUserActivities(ctx interface{}, req interface{}, tenantID interface{}) *MockUserActivityUseCase_GetUserActivities_Call {
	return &MockUserActivityUseCase_GetUserActivities_Call{Call: _e.mock.On("GetUserActivities", ctx, req, tenantID)}
}

func (_c *MockUserActivityUseCase_GetUserActivities_Call) Run(run func(ctx context.Context, req user.GetActivitiesRequest, tenantID string)) *MockUserActivityUseCase_GetUserActivities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.GetActivitiesRequest), args[2].(string))
	})
	return _c
}

func (_c *MockUserActivityUseCase_GetUserActivities_Call) Return(_a0 *activity.ActivityResponse, _a1 error) *MockUserActivityUseCase_GetUserActivities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserActivityUseCase_GetUserActivities_Call) RunAndReturn(run func(context.Context, user.GetActivitiesRequest, string) (*activity.ActivityResponse, error)) *MockUserActivityUseCase_GetUserActivities_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserActivityUseCase creates a new instance of MockUserActivityUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserActivityUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserActivityUseCase {
	mock := &MockUserActivityUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
