// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ai "github.com/memberclass-backend-golang/internal/domain/dto/request/ai"

	lesson "github.com/memberclass-backend-golang/internal/domain/dto/request/lesson"

	mock "github.com/stretchr/testify/mock"

	responseai "github.com/memberclass-backend-golang/internal/domain/dto/response/ai"

	responselesson "github.com/memberclass-backend-golang/internal/domain/dto/response/lesson"
)

// MockAILessonUseCase is an autogenerated mock type for the AILessonUseCase type
type MockAILessonUseCase struct {
	mock.Mock
}

type MockAILessonUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAILessonUseCase) EXPECT() *MockAILessonUseCase_Expecter {
	return &MockAILessonUseCase_Expecter{mock: &_m.Mock}
}

// GetLessons provides a mock function with given fields: ctx, req
func (_m *MockAILessonUseCase) GetLessons(ctx context.Context, req ai.GetAILessonsRequest) (*responseai.AILessonsResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLessons")
	}

	var r0 *responseai.AILessonsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ai.GetAILessonsRequest) (*responseai.AILessonsResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ai.GetAILessonsRequest) *responseai.AILessonsResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responseai.AILessonsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ai.GetAILessonsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAILessonUseCase_GetLessons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessons'
type MockAILessonUseCase_GetLessons_Call struct {
	*mock.Call
}

// GetLessons is a helper method to define mock.On call
//   - ctx context.Context
//   - req ai.GetAILessonsRequest
func (_e *MockAILessonUseCase_Expecter) GetLessons(ctx interface{}, req interface{}) *MockAILessonUseCase_GetLessons_Call {
	return &MockAILessonUseCase_GetLessons_Call{Call: _e.mock.On("GetLessons", ctx, req)}
}

func (_c *MockAILessonUseCase_GetLessons_Call) Run(run func(ctx context.Context, req ai.GetAILessonsRequest)) *MockAILessonUseCase_GetLessons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ai.GetAILessonsRequest))
	})
	return _c
}

func (_c *MockAILessonUseCase_GetLessons_Call) Return(_a0 *responseai.AILessonsResponse, _a1 error) *MockAILessonUseCase_GetLessons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAILessonUseCase_GetLessons_Call) RunAndReturn(run func(context.Context, ai.GetAILessonsRequest) (*responseai.AILessonsResponse, error)) *MockAILessonUseCase_GetLessons_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTranscriptionStatus provides a mock function with given fields: ctx, lessonID, req
func (_m *MockAILessonUseCase) UpdateTranscriptionStatus(ctx context.Context, lessonID string, req lesson.UpdateLessonTranscriptionRequest) (*responselesson.LessonTranscriptionResponse, error) {
	ret := _m.Called(ctx, lessonID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTranscriptionStatus")
	}

	var r0 *responselesson.LessonTranscriptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, lesson.UpdateLessonTranscriptionRequest) (*responselesson.LessonTranscriptionResponse, error)); ok {
		return rf(ctx, lessonID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, lesson.UpdateLessonTranscriptionRequest) *responselesson.LessonTranscriptionResponse); ok {
		r0 = rf(ctx, lessonID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responselesson.LessonTranscriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, lesson.UpdateLessonTranscriptionRequest) error); ok {
		r1 = rf(ctx, lessonID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAILessonUseCase_UpdateTranscriptionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTranscriptionStatus'
type MockAILessonUseCase_UpdateTranscriptionStatus_Call struct {
	*mock.Call
}

// UpdateTranscriptionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - req lesson.UpdateLessonTranscriptionRequest
func (_e *MockAILessonUseCase_Expecter) UpdateTranscriptionStatus(ctx interface{}, lessonID interface{}, req interface{}) *MockAILessonUseCase_UpdateTranscriptionStatus_Call {
	return &MockAILessonUseCase_UpdateTranscriptionStatus_Call{Call: _e.mock.On("UpdateTranscriptionStatus", ctx, lessonID, req)}
}

func (_c *MockAILessonUseCase_UpdateTranscriptionStatus_Call) Run(run func(ctx context.Context, lessonID string, req lesson.UpdateLessonTranscriptionRequest)) *MockAILessonUseCase_UpdateTranscriptionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(lesson.UpdateLessonTranscriptionRequest))
	})
	return _c
}

func (_c *MockAILessonUseCase_UpdateTranscriptionStatus_Call) Return(_a0 *responselesson.LessonTranscriptionResponse, _a1 error) *MockAILessonUseCase_UpdateTranscriptionStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAILessonUseCase_UpdateTranscriptionStatus_Call) RunAndReturn(run func(context.Context, string, lesson.UpdateLessonTranscriptionRequest) (*responselesson.LessonTranscriptionResponse, error)) *MockAILessonUseCase_UpdateTranscriptionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAILessonUseCase creates a new instance of MockAILessonUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAILessonUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAILessonUseCase {
	mock := &MockAILessonUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
