// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, urlOrKey
func (_m *MockStorage) Delete(ctx context.Context, urlOrKey string) error {
	ret := _m.Called(ctx, urlOrKey)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, urlOrKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - urlOrKey string
func (_e *MockStorage_Expecter) Delete(ctx interface{}, urlOrKey interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, urlOrKey)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, urlOrKey string)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, urlOrKey
func (_m *MockStorage) Download(ctx context.Context, urlOrKey string) ([]byte, error) {
	ret := _m.Called(ctx, urlOrKey)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, urlOrKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, urlOrKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, urlOrKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - urlOrKey string
func (_e *MockStorage_Expecter) Download(ctx interface{}, urlOrKey interface{}) *MockStorage_Download_Call {
	return &MockStorage_Download_Call{Call: _e.mock.On("Download", ctx, urlOrKey)}
}

func (_c *MockStorage_Download_Call) Run(run func(ctx context.Context, urlOrKey string)) *MockStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Download_Call) Return(_a0 []byte, _a1 error) *MockStorage_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Download_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, urlOrKey
func (_m *MockStorage) Exists(ctx context.Context, urlOrKey string) (bool, error) {
	ret := _m.Called(ctx, urlOrKey)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, urlOrKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, urlOrKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, urlOrKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - urlOrKey string
func (_e *MockStorage_Expecter) Exists(ctx interface{}, urlOrKey interface{}) *MockStorage_Exists_Call {
	return &MockStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, urlOrKey)}
}

func (_c *MockStorage_Exists_Call) Run(run func(ctx context.Context, urlOrKey string)) *MockStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Exists_Call) Return(_a0 bool, _a1 error) *MockStorage_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, data, filename, contentType
func (_m *MockStorage) Upload(ctx context.Context, data []byte, filename string, contentType string) (string, error) {
	ret := _m.Called(ctx, data, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) (string, error)); ok {
		return rf(ctx, data, filename, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string) string); ok {
		r0 = rf(ctx, data, filename, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string) error); ok {
		r1 = rf(ctx, data, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
//   - filename string
//   - contentType string
func (_e *MockStorage_Expecter) Upload(ctx interface{}, data interface{}, filename interface{}, contentType interface{}) *MockStorage_Upload_Call {
	return &MockStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, data, filename, contentType)}
}

func (_c *MockStorage_Upload_Call) Run(run func(ctx context.Context, data []byte, filename string, contentType string)) *MockStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStorage_Upload_Call) Return(_a0 string, _a1 error) *MockStorage_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Upload_Call) RunAndReturn(run func(context.Context, []byte, string, string) (string, error)) *MockStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
