// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockUserInformationsUseCase is an autogenerated mock type for the UserInformationsUseCase type
type MockUserInformationsUseCase struct {
	mock.Mock
}

type MockUserInformationsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserInformationsUseCase) EXPECT() *MockUserInformationsUseCase_Expecter {
	return &MockUserInformationsUseCase_Expecter{mock: &_m.Mock}
}

// GetUserInformations provides a mock function with given fields: ctx, req, tenantID
func (_m *MockUserInformationsUseCase) GetUserInformations(ctx context.Context, req request.GetUserInformationsRequest, tenantID string) (*response.UserInformationsResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInformations")
	}

	var r0 *response.UserInformationsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetUserInformationsRequest, string) (*response.UserInformationsResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetUserInformationsRequest, string) *response.UserInformationsResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserInformationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetUserInformationsRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserInformationsUseCase_GetUserInformations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInformations'
type MockUserInformationsUseCase_GetUserInformations_Call struct {
	*mock.Call
}

// GetUserInformations is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.GetUserInformationsRequest
//   - tenantID string
func (_e *MockUserInformationsUseCase_Expecter) GetUserInformations(ctx interface{}, req interface{}, tenantID interface{}) *MockUserInformationsUseCase_GetUserInformations_Call {
	return &MockUserInformationsUseCase_GetUserInformations_Call{Call: _e.mock.On("GetUserInformations", ctx, req, tenantID)}
}

func (_c *MockUserInformationsUseCase_GetUserInformations_Call) Run(run func(ctx context.Context, req request.GetUserInformationsRequest, tenantID string)) *MockUserInformationsUseCase_GetUserInformations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.GetUserInformationsRequest), args[2].(string))
	})
	return _c
}

func (_c *MockUserInformationsUseCase_GetUserInformations_Call) Return(_a0 *response.UserInformationsResponse, _a1 error) *MockUserInformationsUseCase_GetUserInformations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserInformationsUseCase_GetUserInformations_Call) RunAndReturn(run func(context.Context, request.GetUserInformationsRequest, string) (*response.UserInformationsResponse, error)) *MockUserInformationsUseCase_GetUserInformations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserInformationsUseCase creates a new instance of MockUserInformationsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserInformationsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserInformationsUseCase {
	mock := &MockUserInformationsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
