// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request/comments"
	response "github.com/memberclass-backend-golang/internal/domain/dto/response/social"
	mock "github.com/stretchr/testify/mock"
)

// MockSocialCommentUseCase is an autogenerated mock type for the SocialCommentUseCase type
type MockSocialCommentUseCase struct {
	mock.Mock
}

type MockSocialCommentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocialCommentUseCase) EXPECT() *MockSocialCommentUseCase_Expecter {
	return &MockSocialCommentUseCase_Expecter{mock: &_m.Mock}
}

// CreateOrUpdatePost provides a mock function with given fields: ctx, req, tenantID
func (_m *MockSocialCommentUseCase) CreateOrUpdatePost(ctx context.Context, req request.CreateSocialCommentRequest, tenantID string) (*response.SocialCommentResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdatePost")
	}

	var r0 *response.SocialCommentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.CreateSocialCommentRequest, string) (*response.SocialCommentResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.CreateSocialCommentRequest, string) *response.SocialCommentResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SocialCommentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.CreateSocialCommentRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialCommentUseCase_CreateOrUpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdatePost'
type MockSocialCommentUseCase_CreateOrUpdatePost_Call struct {
	*mock.Call
}

// CreateOrUpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.CreateSocialCommentRequest
//   - tenantID string
func (_e *MockSocialCommentUseCase_Expecter) CreateOrUpdatePost(ctx interface{}, req interface{}, tenantID interface{}) *MockSocialCommentUseCase_CreateOrUpdatePost_Call {
	return &MockSocialCommentUseCase_CreateOrUpdatePost_Call{Call: _e.mock.On("CreateOrUpdatePost", ctx, req, tenantID)}
}

func (_c *MockSocialCommentUseCase_CreateOrUpdatePost_Call) Run(run func(ctx context.Context, req request.CreateSocialCommentRequest, tenantID string)) *MockSocialCommentUseCase_CreateOrUpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.CreateSocialCommentRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSocialCommentUseCase_CreateOrUpdatePost_Call) Return(_a0 *response.SocialCommentResponse, _a1 error) *MockSocialCommentUseCase_CreateOrUpdatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialCommentUseCase_CreateOrUpdatePost_Call) RunAndReturn(run func(context.Context, request.CreateSocialCommentRequest, string) (*response.SocialCommentResponse, error)) *MockSocialCommentUseCase_CreateOrUpdatePost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSocialCommentUseCase creates a new instance of MockSocialCommentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocialCommentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocialCommentUseCase {
	mock := &MockSocialCommentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
