// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	student "github.com/memberclass-backend-golang/internal/domain/dto/response/student"

	time "time"
)

// MockStudentReportRepository is an autogenerated mock type for the StudentReportRepository type
type MockStudentReportRepository struct {
	mock.Mock
}

type MockStudentReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentReportRepository) EXPECT() *MockStudentReportRepository_Expecter {
	return &MockStudentReportRepository_Expecter{mock: &_m.Mock}
}

// GetStudentsReport provides a mock function with given fields: ctx, tenantID, startDate, endDate, page, limit
func (_m *MockStudentReportRepository) GetStudentsReport(ctx context.Context, tenantID string, startDate *time.Time, endDate *time.Time, page int, limit int) ([]student.StudentReport, int64, error) {
	ret := _m.Called(ctx, tenantID, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentsReport")
	}

	var r0 []student.StudentReport
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time, int, int) ([]student.StudentReport, int64, error)); ok {
		return rf(ctx, tenantID, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time, int, int) []student.StudentReport); ok {
		r0 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]student.StudentReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time, *time.Time, int, int) int64); ok {
		r1 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *time.Time, *time.Time, int, int) error); ok {
		r2 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStudentReportRepository_GetStudentsReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentsReport'
type MockStudentReportRepository_GetStudentsReport_Call struct {
	*mock.Call
}

// GetStudentsReport is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - startDate *time.Time
//   - endDate *time.Time
//   - page int
//   - limit int
func (_e *MockStudentReportRepository_Expecter) GetStudentsReport(ctx interface{}, tenantID interface{}, startDate interface{}, endDate interface{}, page interface{}, limit interface{}) *MockStudentReportRepository_GetStudentsReport_Call {
	return &MockStudentReportRepository_GetStudentsReport_Call{Call: _e.mock.On("GetStudentsReport", ctx, tenantID, startDate, endDate, page, limit)}
}

func (_c *MockStudentReportRepository_GetStudentsReport_Call) Run(run func(ctx context.Context, tenantID string, startDate *time.Time, endDate *time.Time, page int, limit int)) *MockStudentReportRepository_GetStudentsReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*time.Time), args[3].(*time.Time), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockStudentReportRepository_GetStudentsReport_Call) Return(_a0 []student.StudentReport, _a1 int64, _a2 error) *MockStudentReportRepository_GetStudentsReport_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStudentReportRepository_GetStudentsReport_Call) RunAndReturn(run func(context.Context, string, *time.Time, *time.Time, int, int) ([]student.StudentReport, int64, error)) *MockStudentReportRepository_GetStudentsReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentReportRepository creates a new instance of MockStudentReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentReportRepository {
	mock := &MockStudentReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
