// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx
func (_m *MockJob) Execute(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJob_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockJob_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockJob_Expecter) Execute(ctx interface{}) *MockJob_Execute_Call {
	return &MockJob_Execute_Call{Call: _e.mock.On("Execute", ctx)}
}

func (_c *MockJob_Execute_Call) Run(run func(ctx context.Context)) *MockJob_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockJob_Execute_Call) Return(_a0 error) *MockJob_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJob_Execute_Call) RunAndReturn(run func(context.Context) error) *MockJob_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockJob) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockJob_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockJob_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockJob_Expecter) Name() *MockJob_Name_Call {
	return &MockJob_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockJob_Name_Call) Run(run func()) *MockJob_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJob_Name_Call) Return(_a0 string) *MockJob_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJob_Name_Call) RunAndReturn(run func() string) *MockJob_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
