// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request/student"
	response "github.com/memberclass-backend-golang/internal/domain/dto/response/student"
	mock "github.com/stretchr/testify/mock"
)

// MockStudentReportUseCase is an autogenerated mock type for the StudentReportUseCase type
type MockStudentReportUseCase struct {
	mock.Mock
}

type MockStudentReportUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentReportUseCase) EXPECT() *MockStudentReportUseCase_Expecter {
	return &MockStudentReportUseCase_Expecter{mock: &_m.Mock}
}

// GetStudentReport provides a mock function with given fields: ctx, req, tenantID
func (_m *MockStudentReportUseCase) GetStudentReport(ctx context.Context, req request.GetStudentReportRequest, tenantID string) (*response.StudentReportResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentReport")
	}

	var r0 *response.StudentReportResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetStudentReportRequest, string) (*response.StudentReportResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetStudentReportRequest, string) *response.StudentReportResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.StudentReportResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetStudentReportRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentReportUseCase_GetStudentReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStudentReport'
type MockStudentReportUseCase_GetStudentReport_Call struct {
	*mock.Call
}

// GetStudentReport is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.GetStudentReportRequest
//   - tenantID string
func (_e *MockStudentReportUseCase_Expecter) GetStudentReport(ctx interface{}, req interface{}, tenantID interface{}) *MockStudentReportUseCase_GetStudentReport_Call {
	return &MockStudentReportUseCase_GetStudentReport_Call{Call: _e.mock.On("GetStudentReport", ctx, req, tenantID)}
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) Run(run func(ctx context.Context, req request.GetStudentReportRequest, tenantID string)) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.GetStudentReportRequest), args[2].(string))
	})
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) Return(_a0 *response.StudentReportResponse, _a1 error) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentReportUseCase_GetStudentReport_Call) RunAndReturn(run func(context.Context, request.GetStudentReportRequest, string) (*response.StudentReportResponse, error)) *MockStudentReportUseCase_GetStudentReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentReportUseCase creates a new instance of MockStudentReportUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentReportUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentReportUseCase {
	mock := &MockStudentReportUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
