// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/memberclass-backend-golang/internal/domain/ports/rate_limit"
	mock "github.com/stretchr/testify/mock"
)

// MockRateLimiterIP is an autogenerated mock type for the RateLimiterIP type
type MockRateLimiterIP struct {
	mock.Mock
}

type MockRateLimiterIP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiterIP) EXPECT() *MockRateLimiterIP_Expecter {
	return &MockRateLimiterIP_Expecter{mock: &_m.Mock}
}

// CheckLimit provides a mock function with given fields: ctx, ip
func (_m *MockRateLimiterIP) CheckLimit(ctx context.Context, ip string) (bool, ports.RateLimitInfo, error) {
	ret := _m.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for CheckLimit")
	}

	var r0 bool
	var r1 ports.RateLimitInfo
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, ports.RateLimitInfo, error)); ok {
		return rf(ctx, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) ports.RateLimitInfo); ok {
		r1 = rf(ctx, ip)
	} else {
		r1 = ret.Get(1).(ports.RateLimitInfo)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, ip)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRateLimiterIP_CheckLimit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckLimit'
type MockRateLimiterIP_CheckLimit_Call struct {
	*mock.Call
}

// CheckLimit is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *MockRateLimiterIP_Expecter) CheckLimit(ctx interface{}, ip interface{}) *MockRateLimiterIP_CheckLimit_Call {
	return &MockRateLimiterIP_CheckLimit_Call{Call: _e.mock.On("CheckLimit", ctx, ip)}
}

func (_c *MockRateLimiterIP_CheckLimit_Call) Run(run func(ctx context.Context, ip string)) *MockRateLimiterIP_CheckLimit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRateLimiterIP_CheckLimit_Call) Return(_a0 bool, _a1 ports.RateLimitInfo, _a2 error) *MockRateLimiterIP_CheckLimit_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRateLimiterIP_CheckLimit_Call) RunAndReturn(run func(context.Context, string) (bool, ports.RateLimitInfo, error)) *MockRateLimiterIP_CheckLimit_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, ip
func (_m *MockRateLimiterIP) Increment(ctx context.Context, ip string) error {
	ret := _m.Called(ctx, ip)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRateLimiterIP_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockRateLimiterIP_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - ip string
func (_e *MockRateLimiterIP_Expecter) Increment(ctx interface{}, ip interface{}) *MockRateLimiterIP_Increment_Call {
	return &MockRateLimiterIP_Increment_Call{Call: _e.mock.On("Increment", ctx, ip)}
}

func (_c *MockRateLimiterIP_Increment_Call) Run(run func(ctx context.Context, ip string)) *MockRateLimiterIP_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRateLimiterIP_Increment_Call) Return(_a0 error) *MockRateLimiterIP_Increment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRateLimiterIP_Increment_Call) RunAndReturn(run func(context.Context, string) error) *MockRateLimiterIP_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiterIP creates a new instance of MockRateLimiterIP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiterIP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiterIP {
	mock := &MockRateLimiterIP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
