// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/memberclass-backend-golang/internal/domain/dto"
	entities "github.com/memberclass-backend-golang/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockPdfProcessorUseCase is an autogenerated mock type for the PdfProcessorUseCase type
type MockPdfProcessorUseCase struct {
	mock.Mock
}

type MockPdfProcessorUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPdfProcessorUseCase) EXPECT() *MockPdfProcessorUseCase_Expecter {
	return &MockPdfProcessorUseCase_Expecter{mock: &_m.Mock}
}

// CleanupOrphanedPages provides a mock function with given fields: ctx
func (_m *MockPdfProcessorUseCase) CleanupOrphanedPages(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphanedPages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPdfProcessorUseCase_CleanupOrphanedPages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOrphanedPages'
type MockPdfProcessorUseCase_CleanupOrphanedPages_Call struct {
	*mock.Call
}

// CleanupOrphanedPages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPdfProcessorUseCase_Expecter) CleanupOrphanedPages(ctx interface{}) *MockPdfProcessorUseCase_CleanupOrphanedPages_Call {
	return &MockPdfProcessorUseCase_CleanupOrphanedPages_Call{Call: _e.mock.On("CleanupOrphanedPages", ctx)}
}

func (_c *MockPdfProcessorUseCase_CleanupOrphanedPages_Call) Run(run func(ctx context.Context)) *MockPdfProcessorUseCase_CleanupOrphanedPages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_CleanupOrphanedPages_Call) Return(_a0 error) *MockPdfProcessorUseCase_CleanupOrphanedPages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPdfProcessorUseCase_CleanupOrphanedPages_Call) RunAndReturn(run func(context.Context) error) *MockPdfProcessorUseCase_CleanupOrphanedPages_Call {
	_c.Call.Return(run)
	return _c
}

// ConvertPdfToImages provides a mock function with given fields: pdfURL
func (_m *MockPdfProcessorUseCase) ConvertPdfToImages(pdfURL string) ([]string, error) {
	ret := _m.Called(pdfURL)

	if len(ret) == 0 {
		panic("no return value specified for ConvertPdfToImages")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(pdfURL)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(pdfURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pdfURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_ConvertPdfToImages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConvertPdfToImages'
type MockPdfProcessorUseCase_ConvertPdfToImages_Call struct {
	*mock.Call
}

// ConvertPdfToImages is a helper method to define mock.On call
//   - pdfURL string
func (_e *MockPdfProcessorUseCase_Expecter) ConvertPdfToImages(pdfURL interface{}) *MockPdfProcessorUseCase_ConvertPdfToImages_Call {
	return &MockPdfProcessorUseCase_ConvertPdfToImages_Call{Call: _e.mock.On("ConvertPdfToImages", pdfURL)}
}

func (_c *MockPdfProcessorUseCase_ConvertPdfToImages_Call) Run(run func(pdfURL string)) *MockPdfProcessorUseCase_ConvertPdfToImages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_ConvertPdfToImages_Call) Return(_a0 []string, _a1 error) *MockPdfProcessorUseCase_ConvertPdfToImages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_ConvertPdfToImages_Call) RunAndReturn(run func(string) ([]string, error)) *MockPdfProcessorUseCase_ConvertPdfToImages_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdatePDFAsset provides a mock function with given fields: ctx, lessonID, pdfURL
func (_m *MockPdfProcessorUseCase) CreateOrUpdatePDFAsset(ctx context.Context, lessonID string, pdfURL string) (*entities.LessonPDFAsset, error) {
	ret := _m.Called(ctx, lessonID, pdfURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdatePDFAsset")
	}

	var r0 *entities.LessonPDFAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.LessonPDFAsset, error)); ok {
		return rf(ctx, lessonID, pdfURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.LessonPDFAsset); ok {
		r0 = rf(ctx, lessonID, pdfURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.LessonPDFAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lessonID, pdfURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdatePDFAsset'
type MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call struct {
	*mock.Call
}

// CreateOrUpdatePDFAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - pdfURL string
func (_e *MockPdfProcessorUseCase_Expecter) CreateOrUpdatePDFAsset(ctx interface{}, lessonID interface{}, pdfURL interface{}) *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call {
	return &MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call{Call: _e.mock.On("CreateOrUpdatePDFAsset", ctx, lessonID, pdfURL)}
}

func (_c *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call) Run(run func(ctx context.Context, lessonID string, pdfURL string)) *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call) Return(_a0 *entities.LessonPDFAsset, _a1 error) *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call) RunAndReturn(run func(context.Context, string, string) (*entities.LessonPDFAsset, error)) *MockPdfProcessorUseCase_CreateOrUpdatePDFAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetLessonWithPDFAsset provides a mock function with given fields: ctx, lessonID
func (_m *MockPdfProcessorUseCase) GetLessonWithPDFAsset(ctx context.Context, lessonID string) (*entities.Lesson, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonWithPDFAsset")
	}

	var r0 *entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Lesson, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Lesson); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessonWithPDFAsset'
type MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call struct {
	*mock.Call
}

// GetLessonWithPDFAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockPdfProcessorUseCase_Expecter) GetLessonWithPDFAsset(ctx interface{}, lessonID interface{}) *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call {
	return &MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call{Call: _e.mock.On("GetLessonWithPDFAsset", ctx, lessonID)}
}

func (_c *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call) Run(run func(ctx context.Context, lessonID string)) *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call) Return(_a0 *entities.Lesson, _a1 error) *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call) RunAndReturn(run func(context.Context, string) (*entities.Lesson, error)) *MockPdfProcessorUseCase_GetLessonWithPDFAsset_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessAllPendingLessons provides a mock function with given fields: ctx, limit
func (_m *MockPdfProcessorUseCase) ProcessAllPendingLessons(ctx context.Context, limit int) (*dto.BatchProcessResult, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAllPendingLessons")
	}

	var r0 *dto.BatchProcessResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*dto.BatchProcessResult, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *dto.BatchProcessResult); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BatchProcessResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_ProcessAllPendingLessons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAllPendingLessons'
type MockPdfProcessorUseCase_ProcessAllPendingLessons_Call struct {
	*mock.Call
}

// ProcessAllPendingLessons is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockPdfProcessorUseCase_Expecter) ProcessAllPendingLessons(ctx interface{}, limit interface{}) *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call {
	return &MockPdfProcessorUseCase_ProcessAllPendingLessons_Call{Call: _e.mock.On("ProcessAllPendingLessons", ctx, limit)}
}

func (_c *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call) Run(run func(ctx context.Context, limit int)) *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call) Return(_a0 *dto.BatchProcessResult, _a1 error) *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call) RunAndReturn(run func(context.Context, int) (*dto.BatchProcessResult, error)) *MockPdfProcessorUseCase_ProcessAllPendingLessons_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessLesson provides a mock function with given fields: ctx, lessonID
func (_m *MockPdfProcessorUseCase) ProcessLesson(ctx context.Context, lessonID string) (*dto.ProcessResult, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessLesson")
	}

	var r0 *dto.ProcessResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dto.ProcessResult, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dto.ProcessResult); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ProcessResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_ProcessLesson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessLesson'
type MockPdfProcessorUseCase_ProcessLesson_Call struct {
	*mock.Call
}

// ProcessLesson is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockPdfProcessorUseCase_Expecter) ProcessLesson(ctx interface{}, lessonID interface{}) *MockPdfProcessorUseCase_ProcessLesson_Call {
	return &MockPdfProcessorUseCase_ProcessLesson_Call{Call: _e.mock.On("ProcessLesson", ctx, lessonID)}
}

func (_c *MockPdfProcessorUseCase_ProcessLesson_Call) Run(run func(ctx context.Context, lessonID string)) *MockPdfProcessorUseCase_ProcessLesson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_ProcessLesson_Call) Return(_a0 *dto.ProcessResult, _a1 error) *MockPdfProcessorUseCase_ProcessLesson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_ProcessLesson_Call) RunAndReturn(run func(context.Context, string) (*dto.ProcessResult, error)) *MockPdfProcessorUseCase_ProcessLesson_Call {
	_c.Call.Return(run)
	return _c
}

// RegeneratePDF provides a mock function with given fields: ctx, lessonID
func (_m *MockPdfProcessorUseCase) RegeneratePDF(ctx context.Context, lessonID string) error {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for RegeneratePDF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, lessonID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPdfProcessorUseCase_RegeneratePDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegeneratePDF'
type MockPdfProcessorUseCase_RegeneratePDF_Call struct {
	*mock.Call
}

// RegeneratePDF is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockPdfProcessorUseCase_Expecter) RegeneratePDF(ctx interface{}, lessonID interface{}) *MockPdfProcessorUseCase_RegeneratePDF_Call {
	return &MockPdfProcessorUseCase_RegeneratePDF_Call{Call: _e.mock.On("RegeneratePDF", ctx, lessonID)}
}

func (_c *MockPdfProcessorUseCase_RegeneratePDF_Call) Run(run func(ctx context.Context, lessonID string)) *MockPdfProcessorUseCase_RegeneratePDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_RegeneratePDF_Call) Return(_a0 error) *MockPdfProcessorUseCase_RegeneratePDF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPdfProcessorUseCase_RegeneratePDF_Call) RunAndReturn(run func(context.Context, string) error) *MockPdfProcessorUseCase_RegeneratePDF_Call {
	_c.Call.Return(run)
	return _c
}

// RetryFailedAssets provides a mock function with given fields: ctx
func (_m *MockPdfProcessorUseCase) RetryFailedAssets(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetryFailedAssets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPdfProcessorUseCase_RetryFailedAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryFailedAssets'
type MockPdfProcessorUseCase_RetryFailedAssets_Call struct {
	*mock.Call
}

// RetryFailedAssets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPdfProcessorUseCase_Expecter) RetryFailedAssets(ctx interface{}) *MockPdfProcessorUseCase_RetryFailedAssets_Call {
	return &MockPdfProcessorUseCase_RetryFailedAssets_Call{Call: _e.mock.On("RetryFailedAssets", ctx)}
}

func (_c *MockPdfProcessorUseCase_RetryFailedAssets_Call) Run(run func(ctx context.Context)) *MockPdfProcessorUseCase_RetryFailedAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_RetryFailedAssets_Call) Return(_a0 error) *MockPdfProcessorUseCase_RetryFailedAssets_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPdfProcessorUseCase_RetryFailedAssets_Call) RunAndReturn(run func(context.Context) error) *MockPdfProcessorUseCase_RetryFailedAssets_Call {
	_c.Call.Return(run)
	return _c
}

// SavePagesDirectly provides a mock function with given fields: ctx, assetID, lessonID, images
func (_m *MockPdfProcessorUseCase) SavePagesDirectly(ctx context.Context, assetID string, lessonID string, images []string) (int, error) {
	ret := _m.Called(ctx, assetID, lessonID, images)

	if len(ret) == 0 {
		panic("no return value specified for SavePagesDirectly")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) (int, error)); ok {
		return rf(ctx, assetID, lessonID, images)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []string) int); ok {
		r0 = rf(ctx, assetID, lessonID, images)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []string) error); ok {
		r1 = rf(ctx, assetID, lessonID, images)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessorUseCase_SavePagesDirectly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePagesDirectly'
type MockPdfProcessorUseCase_SavePagesDirectly_Call struct {
	*mock.Call
}

// SavePagesDirectly is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - lessonID string
//   - images []string
func (_e *MockPdfProcessorUseCase_Expecter) SavePagesDirectly(ctx interface{}, assetID interface{}, lessonID interface{}, images interface{}) *MockPdfProcessorUseCase_SavePagesDirectly_Call {
	return &MockPdfProcessorUseCase_SavePagesDirectly_Call{Call: _e.mock.On("SavePagesDirectly", ctx, assetID, lessonID, images)}
}

func (_c *MockPdfProcessorUseCase_SavePagesDirectly_Call) Run(run func(ctx context.Context, assetID string, lessonID string, images []string)) *MockPdfProcessorUseCase_SavePagesDirectly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_SavePagesDirectly_Call) Return(_a0 int, _a1 error) *MockPdfProcessorUseCase_SavePagesDirectly_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessorUseCase_SavePagesDirectly_Call) RunAndReturn(run func(context.Context, string, string, []string) (int, error)) *MockPdfProcessorUseCase_SavePagesDirectly_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateLessonHasPDF provides a mock function with given fields: ctx, lessonID
func (_m *MockPdfProcessorUseCase) ValidateLessonHasPDF(ctx context.Context, lessonID string) error {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateLessonHasPDF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, lessonID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPdfProcessorUseCase_ValidateLessonHasPDF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateLessonHasPDF'
type MockPdfProcessorUseCase_ValidateLessonHasPDF_Call struct {
	*mock.Call
}

// ValidateLessonHasPDF is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockPdfProcessorUseCase_Expecter) ValidateLessonHasPDF(ctx interface{}, lessonID interface{}) *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call {
	return &MockPdfProcessorUseCase_ValidateLessonHasPDF_Call{Call: _e.mock.On("ValidateLessonHasPDF", ctx, lessonID)}
}

func (_c *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call) Run(run func(ctx context.Context, lessonID string)) *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call) Return(_a0 error) *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call) RunAndReturn(run func(context.Context, string) error) *MockPdfProcessorUseCase_ValidateLessonHasPDF_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPdfProcessorUseCase creates a new instance of MockPdfProcessorUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPdfProcessorUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPdfProcessorUseCase {
	mock := &MockPdfProcessorUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
