// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/memberclass-backend-golang/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"

	ports "github.com/memberclass-backend-golang/internal/domain/ports"
	response "github.com/memberclass-backend-golang/internal/domain/dto/response"

	time "time"
)

// MockLessonRepository is an autogenerated mock type for the LessonRepository type
type MockLessonRepository struct {
	mock.Mock
}

type MockLessonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonRepository) EXPECT() *MockLessonRepository_Expecter {
	return &MockLessonRepository_Expecter{mock: &_m.Mock}
}

// CreatePDFAsset provides a mock function with given fields: ctx, asset
func (_m *MockLessonRepository) CreatePDFAsset(ctx context.Context, asset *entities.LessonPDFAsset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for CreatePDFAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.LessonPDFAsset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_CreatePDFAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePDFAsset'
type MockLessonRepository_CreatePDFAsset_Call struct {
	*mock.Call
}

// CreatePDFAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *entities.LessonPDFAsset
func (_e *MockLessonRepository_Expecter) CreatePDFAsset(ctx interface{}, asset interface{}) *MockLessonRepository_CreatePDFAsset_Call {
	return &MockLessonRepository_CreatePDFAsset_Call{Call: _e.mock.On("CreatePDFAsset", ctx, asset)}
}

func (_c *MockLessonRepository_CreatePDFAsset_Call) Run(run func(ctx context.Context, asset *entities.LessonPDFAsset)) *MockLessonRepository_CreatePDFAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.LessonPDFAsset))
	})
	return _c
}

func (_c *MockLessonRepository_CreatePDFAsset_Call) Return(_a0 error) *MockLessonRepository_CreatePDFAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_CreatePDFAsset_Call) RunAndReturn(run func(context.Context, *entities.LessonPDFAsset) error) *MockLessonRepository_CreatePDFAsset_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePDFPage provides a mock function with given fields: ctx, page
func (_m *MockLessonRepository) CreatePDFPage(ctx context.Context, page *entities.LessonPDFPage) error {
	ret := _m.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for CreatePDFPage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.LessonPDFPage) error); ok {
		r0 = rf(ctx, page)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_CreatePDFPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePDFPage'
type MockLessonRepository_CreatePDFPage_Call struct {
	*mock.Call
}

// CreatePDFPage is a helper method to define mock.On call
//   - ctx context.Context
//   - page *entities.LessonPDFPage
func (_e *MockLessonRepository_Expecter) CreatePDFPage(ctx interface{}, page interface{}) *MockLessonRepository_CreatePDFPage_Call {
	return &MockLessonRepository_CreatePDFPage_Call{Call: _e.mock.On("CreatePDFPage", ctx, page)}
}

func (_c *MockLessonRepository_CreatePDFPage_Call) Run(run func(ctx context.Context, page *entities.LessonPDFPage)) *MockLessonRepository_CreatePDFPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.LessonPDFPage))
	})
	return _c
}

func (_c *MockLessonRepository_CreatePDFPage_Call) Return(_a0 error) *MockLessonRepository_CreatePDFPage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_CreatePDFPage_Call) RunAndReturn(run func(context.Context, *entities.LessonPDFPage) error) *MockLessonRepository_CreatePDFPage_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePDFPage provides a mock function with given fields: ctx, pageID
func (_m *MockLessonRepository) DeletePDFPage(ctx context.Context, pageID string) error {
	ret := _m.Called(ctx, pageID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePDFPage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, pageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_DeletePDFPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePDFPage'
type MockLessonRepository_DeletePDFPage_Call struct {
	*mock.Call
}

// DeletePDFPage is a helper method to define mock.On call
//   - ctx context.Context
//   - pageID string
func (_e *MockLessonRepository_Expecter) DeletePDFPage(ctx interface{}, pageID interface{}) *MockLessonRepository_DeletePDFPage_Call {
	return &MockLessonRepository_DeletePDFPage_Call{Call: _e.mock.On("DeletePDFPage", ctx, pageID)}
}

func (_c *MockLessonRepository_DeletePDFPage_Call) Run(run func(ctx context.Context, pageID string)) *MockLessonRepository_DeletePDFPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_DeletePDFPage_Call) Return(_a0 error) *MockLessonRepository_DeletePDFPage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_DeletePDFPage_Call) RunAndReturn(run func(context.Context, string) error) *MockLessonRepository_DeletePDFPage_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePDFPagesByAssetID provides a mock function with given fields: ctx, assetID
func (_m *MockLessonRepository) DeletePDFPagesByAssetID(ctx context.Context, assetID string) error {
	ret := _m.Called(ctx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePDFPagesByAssetID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, assetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_DeletePDFPagesByAssetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePDFPagesByAssetID'
type MockLessonRepository_DeletePDFPagesByAssetID_Call struct {
	*mock.Call
}

// DeletePDFPagesByAssetID is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
func (_e *MockLessonRepository_Expecter) DeletePDFPagesByAssetID(ctx interface{}, assetID interface{}) *MockLessonRepository_DeletePDFPagesByAssetID_Call {
	return &MockLessonRepository_DeletePDFPagesByAssetID_Call{Call: _e.mock.On("DeletePDFPagesByAssetID", ctx, assetID)}
}

func (_c *MockLessonRepository_DeletePDFPagesByAssetID_Call) Run(run func(ctx context.Context, assetID string)) *MockLessonRepository_DeletePDFPagesByAssetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_DeletePDFPagesByAssetID_Call) Return(_a0 error) *MockLessonRepository_DeletePDFPagesByAssetID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_DeletePDFPagesByAssetID_Call) RunAndReturn(run func(context.Context, string) error) *MockLessonRepository_DeletePDFPagesByAssetID_Call {
	_c.Call.Return(run)
	return _c
}

// FindCompletedLessonsByEmail provides a mock function with given fields: ctx, userID, tenantID, startDate, endDate, courseID, page, limit
func (_m *MockLessonRepository) FindCompletedLessonsByEmail(ctx context.Context, userID string, tenantID string, startDate time.Time, endDate time.Time, courseID string, page int, limit int) ([]response.CompletedLesson, int64, error) {
	ret := _m.Called(ctx, userID, tenantID, startDate, endDate, courseID, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindCompletedLessonsByEmail")
	}

	var r0 []response.CompletedLesson
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time, string, int, int) ([]response.CompletedLesson, int64, error)); ok {
		return rf(ctx, userID, tenantID, startDate, endDate, courseID, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time, string, int, int) []response.CompletedLesson); ok {
		r0 = rf(ctx, userID, tenantID, startDate, endDate, courseID, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.CompletedLesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time, string, int, int) int64); ok {
		r1 = rf(ctx, userID, tenantID, startDate, endDate, courseID, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, time.Time, time.Time, string, int, int) error); ok {
		r2 = rf(ctx, userID, tenantID, startDate, endDate, courseID, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLessonRepository_FindCompletedLessonsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCompletedLessonsByEmail'
type MockLessonRepository_FindCompletedLessonsByEmail_Call struct {
	*mock.Call
}

// FindCompletedLessonsByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
//   - startDate time.Time
//   - endDate time.Time
//   - courseID string
//   - page int
//   - limit int
func (_e *MockLessonRepository_Expecter) FindCompletedLessonsByEmail(ctx interface{}, userID interface{}, tenantID interface{}, startDate interface{}, endDate interface{}, courseID interface{}, page interface{}, limit interface{}) *MockLessonRepository_FindCompletedLessonsByEmail_Call {
	return &MockLessonRepository_FindCompletedLessonsByEmail_Call{Call: _e.mock.On("FindCompletedLessonsByEmail", ctx, userID, tenantID, startDate, endDate, courseID, page, limit)}
}

func (_c *MockLessonRepository_FindCompletedLessonsByEmail_Call) Run(run func(ctx context.Context, userID string, tenantID string, startDate time.Time, endDate time.Time, courseID string, page int, limit int)) *MockLessonRepository_FindCompletedLessonsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time), args[5].(string), args[6].(int), args[7].(int))
	})
	return _c
}

func (_c *MockLessonRepository_FindCompletedLessonsByEmail_Call) Return(_a0 []response.CompletedLesson, _a1 int64, _a2 error) *MockLessonRepository_FindCompletedLessonsByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLessonRepository_FindCompletedLessonsByEmail_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time, string, int, int) ([]response.CompletedLesson, int64, error)) *MockLessonRepository_FindCompletedLessonsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockLessonRepository) GetByID(ctx context.Context, id string) (*entities.Lesson, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Lesson, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Lesson); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockLessonRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockLessonRepository_GetByID_Call {
	return &MockLessonRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockLessonRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) Return(_a0 *entities.Lesson, _a1 error) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*entities.Lesson, error)) *MockLessonRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithPDFAsset provides a mock function with given fields: ctx, id
func (_m *MockLessonRepository) GetByIDWithPDFAsset(ctx context.Context, id string) (*entities.Lesson, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithPDFAsset")
	}

	var r0 *entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Lesson, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Lesson); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetByIDWithPDFAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithPDFAsset'
type MockLessonRepository_GetByIDWithPDFAsset_Call struct {
	*mock.Call
}

// GetByIDWithPDFAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockLessonRepository_Expecter) GetByIDWithPDFAsset(ctx interface{}, id interface{}) *MockLessonRepository_GetByIDWithPDFAsset_Call {
	return &MockLessonRepository_GetByIDWithPDFAsset_Call{Call: _e.mock.On("GetByIDWithPDFAsset", ctx, id)}
}

func (_c *MockLessonRepository_GetByIDWithPDFAsset_Call) Run(run func(ctx context.Context, id string)) *MockLessonRepository_GetByIDWithPDFAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_GetByIDWithPDFAsset_Call) Return(_a0 *entities.Lesson, _a1 error) *MockLessonRepository_GetByIDWithPDFAsset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetByIDWithPDFAsset_Call) RunAndReturn(run func(context.Context, string) (*entities.Lesson, error)) *MockLessonRepository_GetByIDWithPDFAsset_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDWithTenant provides a mock function with given fields: ctx, lessonID
func (_m *MockLessonRepository) GetByIDWithTenant(ctx context.Context, lessonID string) (*entities.Lesson, *entities.Tenant, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDWithTenant")
	}

	var r0 *entities.Lesson
	var r1 *entities.Tenant
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Lesson, *entities.Tenant, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Lesson); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *entities.Tenant); ok {
		r1 = rf(ctx, lessonID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, lessonID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockLessonRepository_GetByIDWithTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDWithTenant'
type MockLessonRepository_GetByIDWithTenant_Call struct {
	*mock.Call
}

// GetByIDWithTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockLessonRepository_Expecter) GetByIDWithTenant(ctx interface{}, lessonID interface{}) *MockLessonRepository_GetByIDWithTenant_Call {
	return &MockLessonRepository_GetByIDWithTenant_Call{Call: _e.mock.On("GetByIDWithTenant", ctx, lessonID)}
}

func (_c *MockLessonRepository_GetByIDWithTenant_Call) Run(run func(ctx context.Context, lessonID string)) *MockLessonRepository_GetByIDWithTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_GetByIDWithTenant_Call) Return(_a0 *entities.Lesson, _a1 *entities.Tenant, _a2 error) *MockLessonRepository_GetByIDWithTenant_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockLessonRepository_GetByIDWithTenant_Call) RunAndReturn(run func(context.Context, string) (*entities.Lesson, *entities.Tenant, error)) *MockLessonRepository_GetByIDWithTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetFailedPDFAssets provides a mock function with given fields: ctx
func (_m *MockLessonRepository) GetFailedPDFAssets(ctx context.Context) ([]*entities.LessonPDFAsset, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFailedPDFAssets")
	}

	var r0 []*entities.LessonPDFAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entities.LessonPDFAsset, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.LessonPDFAsset); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.LessonPDFAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetFailedPDFAssets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFailedPDFAssets'
type MockLessonRepository_GetFailedPDFAssets_Call struct {
	*mock.Call
}

// GetFailedPDFAssets is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLessonRepository_Expecter) GetFailedPDFAssets(ctx interface{}) *MockLessonRepository_GetFailedPDFAssets_Call {
	return &MockLessonRepository_GetFailedPDFAssets_Call{Call: _e.mock.On("GetFailedPDFAssets", ctx)}
}

func (_c *MockLessonRepository_GetFailedPDFAssets_Call) Run(run func(ctx context.Context)) *MockLessonRepository_GetFailedPDFAssets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLessonRepository_GetFailedPDFAssets_Call) Return(_a0 []*entities.LessonPDFAsset, _a1 error) *MockLessonRepository_GetFailedPDFAssets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetFailedPDFAssets_Call) RunAndReturn(run func(context.Context) ([]*entities.LessonPDFAsset, error)) *MockLessonRepository_GetFailedPDFAssets_Call {
	_c.Call.Return(run)
	return _c
}

// GetPDFAssetByLessonID provides a mock function with given fields: ctx, lessonID
func (_m *MockLessonRepository) GetPDFAssetByLessonID(ctx context.Context, lessonID string) (*entities.LessonPDFAsset, error) {
	ret := _m.Called(ctx, lessonID)

	if len(ret) == 0 {
		panic("no return value specified for GetPDFAssetByLessonID")
	}

	var r0 *entities.LessonPDFAsset
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.LessonPDFAsset, error)); ok {
		return rf(ctx, lessonID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.LessonPDFAsset); ok {
		r0 = rf(ctx, lessonID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.LessonPDFAsset)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lessonID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetPDFAssetByLessonID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPDFAssetByLessonID'
type MockLessonRepository_GetPDFAssetByLessonID_Call struct {
	*mock.Call
}

// GetPDFAssetByLessonID is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
func (_e *MockLessonRepository_Expecter) GetPDFAssetByLessonID(ctx interface{}, lessonID interface{}) *MockLessonRepository_GetPDFAssetByLessonID_Call {
	return &MockLessonRepository_GetPDFAssetByLessonID_Call{Call: _e.mock.On("GetPDFAssetByLessonID", ctx, lessonID)}
}

func (_c *MockLessonRepository_GetPDFAssetByLessonID_Call) Run(run func(ctx context.Context, lessonID string)) *MockLessonRepository_GetPDFAssetByLessonID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_GetPDFAssetByLessonID_Call) Return(_a0 *entities.LessonPDFAsset, _a1 error) *MockLessonRepository_GetPDFAssetByLessonID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetPDFAssetByLessonID_Call) RunAndReturn(run func(context.Context, string) (*entities.LessonPDFAsset, error)) *MockLessonRepository_GetPDFAssetByLessonID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPDFPageByAssetAndNumber provides a mock function with given fields: ctx, assetID, pageNumber
func (_m *MockLessonRepository) GetPDFPageByAssetAndNumber(ctx context.Context, assetID string, pageNumber int) (*entities.LessonPDFPage, error) {
	ret := _m.Called(ctx, assetID, pageNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetPDFPageByAssetAndNumber")
	}

	var r0 *entities.LessonPDFPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) (*entities.LessonPDFPage, error)); ok {
		return rf(ctx, assetID, pageNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *entities.LessonPDFPage); ok {
		r0 = rf(ctx, assetID, pageNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.LessonPDFPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, assetID, pageNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetPDFPageByAssetAndNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPDFPageByAssetAndNumber'
type MockLessonRepository_GetPDFPageByAssetAndNumber_Call struct {
	*mock.Call
}

// GetPDFPageByAssetAndNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - pageNumber int
func (_e *MockLessonRepository_Expecter) GetPDFPageByAssetAndNumber(ctx interface{}, assetID interface{}, pageNumber interface{}) *MockLessonRepository_GetPDFPageByAssetAndNumber_Call {
	return &MockLessonRepository_GetPDFPageByAssetAndNumber_Call{Call: _e.mock.On("GetPDFPageByAssetAndNumber", ctx, assetID, pageNumber)}
}

func (_c *MockLessonRepository_GetPDFPageByAssetAndNumber_Call) Run(run func(ctx context.Context, assetID string, pageNumber int)) *MockLessonRepository_GetPDFPageByAssetAndNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockLessonRepository_GetPDFPageByAssetAndNumber_Call) Return(_a0 *entities.LessonPDFPage, _a1 error) *MockLessonRepository_GetPDFPageByAssetAndNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetPDFPageByAssetAndNumber_Call) RunAndReturn(run func(context.Context, string, int) (*entities.LessonPDFPage, error)) *MockLessonRepository_GetPDFPageByAssetAndNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetPDFPagesByAssetID provides a mock function with given fields: ctx, assetID
func (_m *MockLessonRepository) GetPDFPagesByAssetID(ctx context.Context, assetID string) ([]*entities.LessonPDFPage, error) {
	ret := _m.Called(ctx, assetID)

	if len(ret) == 0 {
		panic("no return value specified for GetPDFPagesByAssetID")
	}

	var r0 []*entities.LessonPDFPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*entities.LessonPDFPage, error)); ok {
		return rf(ctx, assetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*entities.LessonPDFPage); ok {
		r0 = rf(ctx, assetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.LessonPDFPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, assetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetPDFPagesByAssetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPDFPagesByAssetID'
type MockLessonRepository_GetPDFPagesByAssetID_Call struct {
	*mock.Call
}

// GetPDFPagesByAssetID is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
func (_e *MockLessonRepository_Expecter) GetPDFPagesByAssetID(ctx interface{}, assetID interface{}) *MockLessonRepository_GetPDFPagesByAssetID_Call {
	return &MockLessonRepository_GetPDFPagesByAssetID_Call{Call: _e.mock.On("GetPDFPagesByAssetID", ctx, assetID)}
}

func (_c *MockLessonRepository_GetPDFPagesByAssetID_Call) Run(run func(ctx context.Context, assetID string)) *MockLessonRepository_GetPDFPagesByAssetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLessonRepository_GetPDFPagesByAssetID_Call) Return(_a0 []*entities.LessonPDFPage, _a1 error) *MockLessonRepository_GetPDFPagesByAssetID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetPDFPagesByAssetID_Call) RunAndReturn(run func(context.Context, string) ([]*entities.LessonPDFPage, error)) *MockLessonRepository_GetPDFPagesByAssetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingPDFLessons provides a mock function with given fields: ctx, limit
func (_m *MockLessonRepository) GetPendingPDFLessons(ctx context.Context, limit int) ([]*entities.Lesson, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingPDFLessons")
	}

	var r0 []*entities.Lesson
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*entities.Lesson, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*entities.Lesson); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Lesson)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetPendingPDFLessons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingPDFLessons'
type MockLessonRepository_GetPendingPDFLessons_Call struct {
	*mock.Call
}

// GetPendingPDFLessons is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockLessonRepository_Expecter) GetPendingPDFLessons(ctx interface{}, limit interface{}) *MockLessonRepository_GetPendingPDFLessons_Call {
	return &MockLessonRepository_GetPendingPDFLessons_Call{Call: _e.mock.On("GetPendingPDFLessons", ctx, limit)}
}

func (_c *MockLessonRepository_GetPendingPDFLessons_Call) Run(run func(ctx context.Context, limit int)) *MockLessonRepository_GetPendingPDFLessons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockLessonRepository_GetPendingPDFLessons_Call) Return(_a0 []*entities.Lesson, _a1 error) *MockLessonRepository_GetPendingPDFLessons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetPendingPDFLessons_Call) RunAndReturn(run func(context.Context, int) ([]*entities.Lesson, error)) *MockLessonRepository_GetPendingPDFLessons_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, lesson
func (_m *MockLessonRepository) Update(ctx context.Context, lesson *entities.Lesson) error {
	ret := _m.Called(ctx, lesson)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Lesson) error); ok {
		r0 = rf(ctx, lesson)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLessonRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - lesson *entities.Lesson
func (_e *MockLessonRepository_Expecter) Update(ctx interface{}, lesson interface{}) *MockLessonRepository_Update_Call {
	return &MockLessonRepository_Update_Call{Call: _e.mock.On("Update", ctx, lesson)}
}

func (_c *MockLessonRepository_Update_Call) Run(run func(ctx context.Context, lesson *entities.Lesson)) *MockLessonRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Lesson))
	})
	return _c
}

func (_c *MockLessonRepository_Update_Call) Return(_a0 error) *MockLessonRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_Update_Call) RunAndReturn(run func(context.Context, *entities.Lesson) error) *MockLessonRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePDFAsset provides a mock function with given fields: ctx, asset
func (_m *MockLessonRepository) UpdatePDFAsset(ctx context.Context, asset *entities.LessonPDFAsset) error {
	ret := _m.Called(ctx, asset)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePDFAsset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.LessonPDFAsset) error); ok {
		r0 = rf(ctx, asset)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_UpdatePDFAsset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePDFAsset'
type MockLessonRepository_UpdatePDFAsset_Call struct {
	*mock.Call
}

// UpdatePDFAsset is a helper method to define mock.On call
//   - ctx context.Context
//   - asset *entities.LessonPDFAsset
func (_e *MockLessonRepository_Expecter) UpdatePDFAsset(ctx interface{}, asset interface{}) *MockLessonRepository_UpdatePDFAsset_Call {
	return &MockLessonRepository_UpdatePDFAsset_Call{Call: _e.mock.On("UpdatePDFAsset", ctx, asset)}
}

func (_c *MockLessonRepository_UpdatePDFAsset_Call) Run(run func(ctx context.Context, asset *entities.LessonPDFAsset)) *MockLessonRepository_UpdatePDFAsset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.LessonPDFAsset))
	})
	return _c
}

func (_c *MockLessonRepository_UpdatePDFAsset_Call) Return(_a0 error) *MockLessonRepository_UpdatePDFAsset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_UpdatePDFAsset_Call) RunAndReturn(run func(context.Context, *entities.LessonPDFAsset) error) *MockLessonRepository_UpdatePDFAsset_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePDFAssetStatus provides a mock function with given fields: ctx, assetID, status, totalPages, errorMsg
func (_m *MockLessonRepository) UpdatePDFAssetStatus(ctx context.Context, assetID string, status string, totalPages *int, errorMsg *string) error {
	ret := _m.Called(ctx, assetID, status, totalPages, errorMsg)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePDFAssetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int, *string) error); ok {
		r0 = rf(ctx, assetID, status, totalPages, errorMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_UpdatePDFAssetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePDFAssetStatus'
type MockLessonRepository_UpdatePDFAssetStatus_Call struct {
	*mock.Call
}

// UpdatePDFAssetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - assetID string
//   - status string
//   - totalPages *int
//   - errorMsg *string
func (_e *MockLessonRepository_Expecter) UpdatePDFAssetStatus(ctx interface{}, assetID interface{}, status interface{}, totalPages interface{}, errorMsg interface{}) *MockLessonRepository_UpdatePDFAssetStatus_Call {
	return &MockLessonRepository_UpdatePDFAssetStatus_Call{Call: _e.mock.On("UpdatePDFAssetStatus", ctx, assetID, status, totalPages, errorMsg)}
}

func (_c *MockLessonRepository_UpdatePDFAssetStatus_Call) Run(run func(ctx context.Context, assetID string, status string, totalPages *int, errorMsg *string)) *MockLessonRepository_UpdatePDFAssetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*int), args[4].(*string))
	})
	return _c
}

func (_c *MockLessonRepository_UpdatePDFAssetStatus_Call) Return(_a0 error) *MockLessonRepository_UpdatePDFAssetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_UpdatePDFAssetStatus_Call) RunAndReturn(run func(context.Context, string, string, *int, *string) error) *MockLessonRepository_UpdatePDFAssetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTranscriptionStatus provides a mock function with given fields: ctx, lessonID, transcriptionCompleted
func (_m *MockLessonRepository) UpdateTranscriptionStatus(ctx context.Context, lessonID string, transcriptionCompleted bool) error {
	ret := _m.Called(ctx, lessonID, transcriptionCompleted)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTranscriptionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, lessonID, transcriptionCompleted)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLessonRepository_UpdateTranscriptionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTranscriptionStatus'
type MockLessonRepository_UpdateTranscriptionStatus_Call struct {
	*mock.Call
}

// UpdateTranscriptionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - transcriptionCompleted bool
func (_e *MockLessonRepository_Expecter) UpdateTranscriptionStatus(ctx interface{}, lessonID interface{}, transcriptionCompleted interface{}) *MockLessonRepository_UpdateTranscriptionStatus_Call {
	return &MockLessonRepository_UpdateTranscriptionStatus_Call{Call: _e.mock.On("UpdateTranscriptionStatus", ctx, lessonID, transcriptionCompleted)}
}

func (_c *MockLessonRepository_UpdateTranscriptionStatus_Call) Run(run func(ctx context.Context, lessonID string, transcriptionCompleted bool)) *MockLessonRepository_UpdateTranscriptionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockLessonRepository_UpdateTranscriptionStatus_Call) Return(_a0 error) *MockLessonRepository_UpdateTranscriptionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLessonRepository_UpdateTranscriptionStatus_Call) RunAndReturn(run func(context.Context, string, bool) error) *MockLessonRepository_UpdateTranscriptionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetLessonsWithHierarchyByTenant provides a mock function with given fields: ctx, tenantID, onlyUnprocessed
func (_m *MockLessonRepository) GetLessonsWithHierarchyByTenant(ctx context.Context, tenantID string, onlyUnprocessed bool) ([]ports.AILessonWithHierarchy, error) {
	ret := _m.Called(ctx, tenantID, onlyUnprocessed)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsWithHierarchyByTenant")
	}

	var r0 []ports.AILessonWithHierarchy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) ([]ports.AILessonWithHierarchy, error)); ok {
		return rf(ctx, tenantID, onlyUnprocessed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) []ports.AILessonWithHierarchy); ok {
		r0 = rf(ctx, tenantID, onlyUnprocessed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.AILessonWithHierarchy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, tenantID, onlyUnprocessed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonRepository_GetLessonsWithHierarchyByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessonsWithHierarchyByTenant'
type MockLessonRepository_GetLessonsWithHierarchyByTenant_Call struct {
	*mock.Call
}

// GetLessonsWithHierarchyByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - onlyUnprocessed bool
func (_e *MockLessonRepository_Expecter) GetLessonsWithHierarchyByTenant(ctx interface{}, tenantID interface{}, onlyUnprocessed interface{}) *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call {
	return &MockLessonRepository_GetLessonsWithHierarchyByTenant_Call{Call: _e.mock.On("GetLessonsWithHierarchyByTenant", ctx, tenantID, onlyUnprocessed)}
}

func (_c *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call) Run(run func(ctx context.Context, tenantID string, onlyUnprocessed bool)) *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call) Return(_a0 []ports.AILessonWithHierarchy, _a1 error) *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call) RunAndReturn(run func(context.Context, string, bool) ([]ports.AILessonWithHierarchy, error)) *MockLessonRepository_GetLessonsWithHierarchyByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonRepository creates a new instance of MockLessonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonRepository {
	mock := &MockLessonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
