// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockUserActivityRepository is an autogenerated mock type for the UserActivityRepository type
type MockUserActivityRepository struct {
	mock.Mock
}

type MockUserActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserActivityRepository) EXPECT() *MockUserActivityRepository_Expecter {
	return &MockUserActivityRepository_Expecter{mock: &_m.Mock}
}

// FindActivitiesByEmail provides a mock function with given fields: ctx, email, page, limit
func (_m *MockUserActivityRepository) FindActivitiesByEmail(ctx context.Context, email string, page int, limit int) ([]response.AccessData, int64, error) {
	ret := _m.Called(ctx, email, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindActivitiesByEmail")
	}

	var r0 []response.AccessData
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]response.AccessData, int64, error)); ok {
		return rf(ctx, email, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []response.AccessData); ok {
		r0 = rf(ctx, email, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.AccessData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, email, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, email, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserActivityRepository_FindActivitiesByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActivitiesByEmail'
type MockUserActivityRepository_FindActivitiesByEmail_Call struct {
	*mock.Call
}

// FindActivitiesByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - page int
//   - limit int
func (_e *MockUserActivityRepository_Expecter) FindActivitiesByEmail(ctx interface{}, email interface{}, page interface{}, limit interface{}) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	return &MockUserActivityRepository_FindActivitiesByEmail_Call{Call: _e.mock.On("FindActivitiesByEmail", ctx, email, page, limit)}
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) Run(run func(ctx context.Context, email string, page int, limit int)) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) Return(_a0 []response.AccessData, _a1 int64, _a2 error) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) RunAndReturn(run func(context.Context, string, int, int) ([]response.AccessData, int64, error)) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserActivityRepository creates a new instance of MockUserActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserActivityRepository {
	mock := &MockUserActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
