// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/memberclass-backend-golang/internal/domain/dto/response/catalog"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

type MockCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogRepository) EXPECT() *MockCatalogRepository_Expecter {
	return &MockCatalogRepository_Expecter{mock: &_m.Mock}
}

// GetCatalogByTenant provides a mock function with given fields: ctx, tenantID
func (_m *MockCatalogRepository) GetCatalogByTenant(ctx context.Context, tenantID string) (*catalog.CatalogResponse, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalogByTenant")
	}

	var r0 *catalog.CatalogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*catalog.CatalogResponse, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.CatalogResponse); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.CatalogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetCatalogByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalogByTenant'
type MockCatalogRepository_GetCatalogByTenant_Call struct {
	*mock.Call
}

// GetCatalogByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockCatalogRepository_Expecter) GetCatalogByTenant(ctx interface{}, tenantID interface{}) *MockCatalogRepository_GetCatalogByTenant_Call {
	return &MockCatalogRepository_GetCatalogByTenant_Call{Call: _e.mock.On("GetCatalogByTenant", ctx, tenantID)}
}

func (_c *MockCatalogRepository_GetCatalogByTenant_Call) Run(run func(ctx context.Context, tenantID string)) *MockCatalogRepository_GetCatalogByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_GetCatalogByTenant_Call) Return(_a0 *catalog.CatalogResponse, _a1 error) *MockCatalogRepository_GetCatalogByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetCatalogByTenant_Call) RunAndReturn(run func(context.Context, string) (*catalog.CatalogResponse, error)) *MockCatalogRepository_GetCatalogByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseByID provides a mock function with given fields: ctx, courseID, tenantID, includeChildren
func (_m *MockCatalogRepository) GetCourseByID(ctx context.Context, courseID string, tenantID string, includeChildren bool) (*catalog.CourseDetailResponse, error) {
	ret := _m.Called(ctx, courseID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByID")
	}

	var r0 *catalog.CourseDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.CourseDetailResponse, error)); ok {
		return rf(ctx, courseID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.CourseDetailResponse); ok {
		r0 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.CourseDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetCourseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseByID'
type MockCatalogRepository_GetCourseByID_Call struct {
	*mock.Call
}

// GetCourseByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogRepository_Expecter) GetCourseByID(ctx interface{}, courseID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogRepository_GetCourseByID_Call {
	return &MockCatalogRepository_GetCourseByID_Call{Call: _e.mock.On("GetCourseByID", ctx, courseID, tenantID, includeChildren)}
}

func (_c *MockCatalogRepository_GetCourseByID_Call) Run(run func(ctx context.Context, courseID string, tenantID string, includeChildren bool)) *MockCatalogRepository_GetCourseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogRepository_GetCourseByID_Call) Return(_a0 *catalog.CourseDetailResponse, _a1 error) *MockCatalogRepository_GetCourseByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetCourseByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.CourseDetailResponse, error)) *MockCatalogRepository_GetCourseByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLessonByID provides a mock function with given fields: ctx, lessonID, tenantID
func (_m *MockCatalogRepository) GetLessonByID(ctx context.Context, lessonID string, tenantID string) (*catalog.LessonDetailResponse, error) {
	ret := _m.Called(ctx, lessonID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonByID")
	}

	var r0 *catalog.LessonDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*catalog.LessonDetailResponse, error)); ok {
		return rf(ctx, lessonID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *catalog.LessonDetailResponse); ok {
		r0 = rf(ctx, lessonID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.LessonDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lessonID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetLessonByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessonByID'
type MockCatalogRepository_GetLessonByID_Call struct {
	*mock.Call
}

// GetLessonByID is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - tenantID string
func (_e *MockCatalogRepository_Expecter) GetLessonByID(ctx interface{}, lessonID interface{}, tenantID interface{}) *MockCatalogRepository_GetLessonByID_Call {
	return &MockCatalogRepository_GetLessonByID_Call{Call: _e.mock.On("GetLessonByID", ctx, lessonID, tenantID)}
}

func (_c *MockCatalogRepository_GetLessonByID_Call) Run(run func(ctx context.Context, lessonID string, tenantID string)) *MockCatalogRepository_GetLessonByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_GetLessonByID_Call) Return(_a0 *catalog.LessonDetailResponse, _a1 error) *MockCatalogRepository_GetLessonByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetLessonByID_Call) RunAndReturn(run func(context.Context, string, string) (*catalog.LessonDetailResponse, error)) *MockCatalogRepository_GetLessonByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetModuleByID provides a mock function with given fields: ctx, moduleID, tenantID, includeChildren
func (_m *MockCatalogRepository) GetModuleByID(ctx context.Context, moduleID string, tenantID string, includeChildren bool) (*catalog.ModuleDetailResponse, error) {
	ret := _m.Called(ctx, moduleID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetModuleByID")
	}

	var r0 *catalog.ModuleDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.ModuleDetailResponse, error)); ok {
		return rf(ctx, moduleID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.ModuleDetailResponse); ok {
		r0 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.ModuleDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetModuleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModuleByID'
type MockCatalogRepository_GetModuleByID_Call struct {
	*mock.Call
}

// GetModuleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - moduleID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogRepository_Expecter) GetModuleByID(ctx interface{}, moduleID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogRepository_GetModuleByID_Call {
	return &MockCatalogRepository_GetModuleByID_Call{Call: _e.mock.On("GetModuleByID", ctx, moduleID, tenantID, includeChildren)}
}

func (_c *MockCatalogRepository_GetModuleByID_Call) Run(run func(ctx context.Context, moduleID string, tenantID string, includeChildren bool)) *MockCatalogRepository_GetModuleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogRepository_GetModuleByID_Call) Return(_a0 *catalog.ModuleDetailResponse, _a1 error) *MockCatalogRepository_GetModuleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetModuleByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.ModuleDetailResponse, error)) *MockCatalogRepository_GetModuleByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVitrineByID provides a mock function with given fields: ctx, vitrineID, tenantID, includeChildren
func (_m *MockCatalogRepository) GetVitrineByID(ctx context.Context, vitrineID string, tenantID string, includeChildren bool) (*catalog.VitrineDetailResponse, error) {
	ret := _m.Called(ctx, vitrineID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrineByID")
	}

	var r0 *catalog.VitrineDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.VitrineDetailResponse, error)); ok {
		return rf(ctx, vitrineID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.VitrineDetailResponse); ok {
		r0 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.VitrineDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetVitrineByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrineByID'
type MockCatalogRepository_GetVitrineByID_Call struct {
	*mock.Call
}

// GetVitrineByID is a helper method to define mock.On call
//   - ctx context.Context
//   - vitrineID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogRepository_Expecter) GetVitrineByID(ctx interface{}, vitrineID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogRepository_GetVitrineByID_Call {
	return &MockCatalogRepository_GetVitrineByID_Call{Call: _e.mock.On("GetVitrineByID", ctx, vitrineID, tenantID, includeChildren)}
}

func (_c *MockCatalogRepository_GetVitrineByID_Call) Run(run func(ctx context.Context, vitrineID string, tenantID string, includeChildren bool)) *MockCatalogRepository_GetVitrineByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogRepository_GetVitrineByID_Call) Return(_a0 *catalog.VitrineDetailResponse, _a1 error) *MockCatalogRepository_GetVitrineByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetVitrineByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.VitrineDetailResponse, error)) *MockCatalogRepository_GetVitrineByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
