// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vitrine "github.com/memberclass-backend-golang/internal/domain/dto/response/vitrine"
)

// MockVitrineRepository is an autogenerated mock type for the VitrineRepository type
type MockVitrineRepository struct {
	mock.Mock
}

type MockVitrineRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVitrineRepository) EXPECT() *MockVitrineRepository_Expecter {
	return &MockVitrineRepository_Expecter{mock: &_m.Mock}
}

// GetVitrinesByTenant provides a mock function with given fields: ctx, tenantID
func (_m *MockVitrineRepository) GetVitrinesByTenant(ctx context.Context, tenantID string) (*vitrine.VitrineResponse, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrinesByTenant")
	}

	var r0 *vitrine.VitrineResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*vitrine.VitrineResponse, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *vitrine.VitrineResponse); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.VitrineResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineRepository_GetVitrinesByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrinesByTenant'
type MockVitrineRepository_GetVitrinesByTenant_Call struct {
	*mock.Call
}

// GetVitrinesByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockVitrineRepository_Expecter) GetVitrinesByTenant(ctx interface{}, tenantID interface{}) *MockVitrineRepository_GetVitrinesByTenant_Call {
	return &MockVitrineRepository_GetVitrinesByTenant_Call{Call: _e.mock.On("GetVitrinesByTenant", ctx, tenantID)}
}

func (_c *MockVitrineRepository_GetVitrinesByTenant_Call) Run(run func(ctx context.Context, tenantID string)) *MockVitrineRepository_GetVitrinesByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVitrineRepository_GetVitrinesByTenant_Call) Return(_a0 *vitrine.VitrineResponse, _a1 error) *MockVitrineRepository_GetVitrinesByTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineRepository_GetVitrinesByTenant_Call) RunAndReturn(run func(context.Context, string) (*vitrine.VitrineResponse, error)) *MockVitrineRepository_GetVitrinesByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourseByID provides a mock function with given fields: ctx, courseID, tenantID, includeChildren
func (_m *MockVitrineRepository) GetCourseByID(ctx context.Context, courseID string, tenantID string, includeChildren bool) (*vitrine.CourseDetailResponse, error) {
	ret := _m.Called(ctx, courseID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetCourseByID")
	}

	var r0 *vitrine.CourseDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.CourseDetailResponse, error)); ok {
		return rf(ctx, courseID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.CourseDetailResponse); ok {
		r0 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.CourseDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineRepository_GetCourseByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourseByID'
type MockVitrineRepository_GetCourseByID_Call struct {
	*mock.Call
}

// GetCourseByID is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineRepository_Expecter) GetCourseByID(ctx interface{}, courseID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineRepository_GetCourseByID_Call {
	return &MockVitrineRepository_GetCourseByID_Call{Call: _e.mock.On("GetCourseByID", ctx, courseID, tenantID, includeChildren)}
}

func (_c *MockVitrineRepository_GetCourseByID_Call) Run(run func(ctx context.Context, courseID string, tenantID string, includeChildren bool)) *MockVitrineRepository_GetCourseByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineRepository_GetCourseByID_Call) Return(_a0 *vitrine.CourseDetailResponse, _a1 error) *MockVitrineRepository_GetCourseByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineRepository_GetCourseByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.CourseDetailResponse, error)) *MockVitrineRepository_GetCourseByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLessonByID provides a mock function with given fields: ctx, lessonID, tenantID
func (_m *MockVitrineRepository) GetLessonByID(ctx context.Context, lessonID string, tenantID string) (*vitrine.LessonDetailResponse, error) {
	ret := _m.Called(ctx, lessonID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonByID")
	}

	var r0 *vitrine.LessonDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*vitrine.LessonDetailResponse, error)); ok {
		return rf(ctx, lessonID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *vitrine.LessonDetailResponse); ok {
		r0 = rf(ctx, lessonID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.LessonDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lessonID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineRepository_GetLessonByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessonByID'
type MockVitrineRepository_GetLessonByID_Call struct {
	*mock.Call
}

// GetLessonByID is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - tenantID string
func (_e *MockVitrineRepository_Expecter) GetLessonByID(ctx interface{}, lessonID interface{}, tenantID interface{}) *MockVitrineRepository_GetLessonByID_Call {
	return &MockVitrineRepository_GetLessonByID_Call{Call: _e.mock.On("GetLessonByID", ctx, lessonID, tenantID)}
}

func (_c *MockVitrineRepository_GetLessonByID_Call) Run(run func(ctx context.Context, lessonID string, tenantID string)) *MockVitrineRepository_GetLessonByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVitrineRepository_GetLessonByID_Call) Return(_a0 *vitrine.LessonDetailResponse, _a1 error) *MockVitrineRepository_GetLessonByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineRepository_GetLessonByID_Call) RunAndReturn(run func(context.Context, string, string) (*vitrine.LessonDetailResponse, error)) *MockVitrineRepository_GetLessonByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetModuleByID provides a mock function with given fields: ctx, moduleID, tenantID, includeChildren
func (_m *MockVitrineRepository) GetModuleByID(ctx context.Context, moduleID string, tenantID string, includeChildren bool) (*vitrine.ModuleDetailResponse, error) {
	ret := _m.Called(ctx, moduleID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetModuleByID")
	}

	var r0 *vitrine.ModuleDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.ModuleDetailResponse, error)); ok {
		return rf(ctx, moduleID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.ModuleDetailResponse); ok {
		r0 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.ModuleDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineRepository_GetModuleByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModuleByID'
type MockVitrineRepository_GetModuleByID_Call struct {
	*mock.Call
}

// GetModuleByID is a helper method to define mock.On call
//   - ctx context.Context
//   - moduleID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineRepository_Expecter) GetModuleByID(ctx interface{}, moduleID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineRepository_GetModuleByID_Call {
	return &MockVitrineRepository_GetModuleByID_Call{Call: _e.mock.On("GetModuleByID", ctx, moduleID, tenantID, includeChildren)}
}

func (_c *MockVitrineRepository_GetModuleByID_Call) Run(run func(ctx context.Context, moduleID string, tenantID string, includeChildren bool)) *MockVitrineRepository_GetModuleByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineRepository_GetModuleByID_Call) Return(_a0 *vitrine.ModuleDetailResponse, _a1 error) *MockVitrineRepository_GetModuleByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineRepository_GetModuleByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.ModuleDetailResponse, error)) *MockVitrineRepository_GetModuleByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVitrineByID provides a mock function with given fields: ctx, vitrineID, tenantID, includeChildren
func (_m *MockVitrineRepository) GetVitrineByID(ctx context.Context, vitrineID string, tenantID string, includeChildren bool) (*vitrine.VitrineDetailResponse, error) {
	ret := _m.Called(ctx, vitrineID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrineByID")
	}

	var r0 *vitrine.VitrineDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.VitrineDetailResponse, error)); ok {
		return rf(ctx, vitrineID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.VitrineDetailResponse); ok {
		r0 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.VitrineDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineRepository_GetVitrineByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrineByID'
type MockVitrineRepository_GetVitrineByID_Call struct {
	*mock.Call
}

// GetVitrineByID is a helper method to define mock.On call
//   - ctx context.Context
//   - vitrineID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineRepository_Expecter) GetVitrineByID(ctx interface{}, vitrineID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineRepository_GetVitrineByID_Call {
	return &MockVitrineRepository_GetVitrineByID_Call{Call: _e.mock.On("GetVitrineByID", ctx, vitrineID, tenantID, includeChildren)}
}

func (_c *MockVitrineRepository_GetVitrineByID_Call) Run(run func(ctx context.Context, vitrineID string, tenantID string, includeChildren bool)) *MockVitrineRepository_GetVitrineByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineRepository_GetVitrineByID_Call) Return(_a0 *vitrine.VitrineDetailResponse, _a1 error) *MockVitrineRepository_GetVitrineByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineRepository_GetVitrineByID_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.VitrineDetailResponse, error)) *MockVitrineRepository_GetVitrineByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVitrineRepository creates a new instance of MockVitrineRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVitrineRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVitrineRepository {
	mock := &MockVitrineRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
