// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/memberclass-backend-golang/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockTenantRepository is an autogenerated mock type for the TenantRepository type
type MockTenantRepository struct {
	mock.Mock
}

type MockTenantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantRepository) EXPECT() *MockTenantRepository_Expecter {
	return &MockTenantRepository_Expecter{mock: &_m.Mock}
}

// FindAllWithAIEnabled provides a mock function with given fields: ctx
func (_m *MockTenantRepository) FindAllWithAIEnabled(ctx context.Context) ([]*entities.Tenant, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAllWithAIEnabled")
	}

	var r0 []*entities.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entities.Tenant, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.Tenant); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindAllWithAIEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllWithAIEnabled'
type MockTenantRepository_FindAllWithAIEnabled_Call struct {
	*mock.Call
}

// FindAllWithAIEnabled is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTenantRepository_Expecter) FindAllWithAIEnabled(ctx interface{}) *MockTenantRepository_FindAllWithAIEnabled_Call {
	return &MockTenantRepository_FindAllWithAIEnabled_Call{Call: _e.mock.On("FindAllWithAIEnabled", ctx)}
}

func (_c *MockTenantRepository_FindAllWithAIEnabled_Call) Run(run func(ctx context.Context)) *MockTenantRepository_FindAllWithAIEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTenantRepository_FindAllWithAIEnabled_Call) Return(_a0 []*entities.Tenant, _a1 error) *MockTenantRepository_FindAllWithAIEnabled_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindAllWithAIEnabled_Call) RunAndReturn(run func(context.Context) ([]*entities.Tenant, error)) *MockTenantRepository_FindAllWithAIEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// FindBunnyInfoByID provides a mock function with given fields: tenantID
func (_m *MockTenantRepository) FindBunnyInfoByID(tenantID string) (*entities.Tenant, error) {
	ret := _m.Called(tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindBunnyInfoByID")
	}

	var r0 *entities.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Tenant, error)); ok {
		return rf(tenantID)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Tenant); ok {
		r0 = rf(tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindBunnyInfoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBunnyInfoByID'
type MockTenantRepository_FindBunnyInfoByID_Call struct {
	*mock.Call
}

// FindBunnyInfoByID is a helper method to define mock.On call
//   - tenantID string
func (_e *MockTenantRepository_Expecter) FindBunnyInfoByID(tenantID interface{}) *MockTenantRepository_FindBunnyInfoByID_Call {
	return &MockTenantRepository_FindBunnyInfoByID_Call{Call: _e.mock.On("FindBunnyInfoByID", tenantID)}
}

func (_c *MockTenantRepository_FindBunnyInfoByID_Call) Run(run func(tenantID string)) *MockTenantRepository_FindBunnyInfoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTenantRepository_FindBunnyInfoByID_Call) Return(_a0 *entities.Tenant, _a1 error) *MockTenantRepository_FindBunnyInfoByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindBunnyInfoByID_Call) RunAndReturn(run func(string) (*entities.Tenant, error)) *MockTenantRepository_FindBunnyInfoByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: tenantID
func (_m *MockTenantRepository) FindByID(tenantID string) (*entities.Tenant, error) {
	ret := _m.Called(tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entities.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.Tenant, error)); ok {
		return rf(tenantID)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.Tenant); ok {
		r0 = rf(tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockTenantRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - tenantID string
func (_e *MockTenantRepository_Expecter) FindByID(tenantID interface{}) *MockTenantRepository_FindByID_Call {
	return &MockTenantRepository_FindByID_Call{Call: _e.mock.On("FindByID", tenantID)}
}

func (_c *MockTenantRepository_FindByID_Call) Run(run func(tenantID string)) *MockTenantRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTenantRepository_FindByID_Call) Return(_a0 *entities.Tenant, _a1 error) *MockTenantRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindByID_Call) RunAndReturn(run func(string) (*entities.Tenant, error)) *MockTenantRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindTenantByToken provides a mock function with given fields: ctx, token
func (_m *MockTenantRepository) FindTenantByToken(ctx context.Context, token string) (*entities.Tenant, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindTenantByToken")
	}

	var r0 *entities.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Tenant, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Tenant); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FindTenantByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTenantByToken'
type MockTenantRepository_FindTenantByToken_Call struct {
	*mock.Call
}

// FindTenantByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTenantRepository_Expecter) FindTenantByToken(ctx interface{}, token interface{}) *MockTenantRepository_FindTenantByToken_Call {
	return &MockTenantRepository_FindTenantByToken_Call{Call: _e.mock.On("FindTenantByToken", ctx, token)}
}

func (_c *MockTenantRepository_FindTenantByToken_Call) Run(run func(ctx context.Context, token string)) *MockTenantRepository_FindTenantByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTenantRepository_FindTenantByToken_Call) Return(_a0 *entities.Tenant, _a1 error) *MockTenantRepository_FindTenantByToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FindTenantByToken_Call) RunAndReturn(run func(context.Context, string) (*entities.Tenant, error)) *MockTenantRepository_FindTenantByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTokenApiAuth provides a mock function with given fields: ctx, tenantID, tokenHash
func (_m *MockTenantRepository) UpdateTokenApiAuth(ctx context.Context, tenantID string, tokenHash string) error {
	ret := _m.Called(ctx, tenantID, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenApiAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, tenantID, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTenantRepository_UpdateTokenApiAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTokenApiAuth'
type MockTenantRepository_UpdateTokenApiAuth_Call struct {
	*mock.Call
}

// UpdateTokenApiAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - tokenHash string
func (_e *MockTenantRepository_Expecter) UpdateTokenApiAuth(ctx interface{}, tenantID interface{}, tokenHash interface{}) *MockTenantRepository_UpdateTokenApiAuth_Call {
	return &MockTenantRepository_UpdateTokenApiAuth_Call{Call: _e.mock.On("UpdateTokenApiAuth", ctx, tenantID, tokenHash)}
}

func (_c *MockTenantRepository_UpdateTokenApiAuth_Call) Run(run func(ctx context.Context, tenantID string, tokenHash string)) *MockTenantRepository_UpdateTokenApiAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTenantRepository_UpdateTokenApiAuth_Call) Return(_a0 error) *MockTenantRepository_UpdateTokenApiAuth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTenantRepository_UpdateTokenApiAuth_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTenantRepository_UpdateTokenApiAuth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantRepository creates a new instance of MockTenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantRepository {
	mock := &MockTenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
