// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
)

// MockLessonsCompletedUseCase is an autogenerated mock type for the LessonsCompletedUseCase type
type MockLessonsCompletedUseCase struct {
	mock.Mock
}

type MockLessonsCompletedUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLessonsCompletedUseCase) EXPECT() *MockLessonsCompletedUseCase_Expecter {
	return &MockLessonsCompletedUseCase_Expecter{mock: &_m.Mock}
}

// GetLessonsCompleted provides a mock function with given fields: ctx, req, tenantID
func (_m *MockLessonsCompletedUseCase) GetLessonsCompleted(ctx context.Context, req request.GetLessonsCompletedRequest, tenantID string) (*response.LessonsCompletedResponse, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsCompleted")
	}

	var r0 *response.LessonsCompletedResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.GetLessonsCompletedRequest, string) (*response.LessonsCompletedResponse, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.GetLessonsCompletedRequest, string) *response.LessonsCompletedResponse); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.LessonsCompletedResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.GetLessonsCompletedRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLessonsCompletedUseCase_GetLessonsCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLessonsCompleted'
type MockLessonsCompletedUseCase_GetLessonsCompleted_Call struct {
	*mock.Call
}

// GetLessonsCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - req request.GetLessonsCompletedRequest
//   - tenantID string
func (_e *MockLessonsCompletedUseCase_Expecter) GetLessonsCompleted(ctx interface{}, req interface{}, tenantID interface{}) *MockLessonsCompletedUseCase_GetLessonsCompleted_Call {
	return &MockLessonsCompletedUseCase_GetLessonsCompleted_Call{Call: _e.mock.On("GetLessonsCompleted", ctx, req, tenantID)}
}

func (_c *MockLessonsCompletedUseCase_GetLessonsCompleted_Call) Run(run func(ctx context.Context, req request.GetLessonsCompletedRequest, tenantID string)) *MockLessonsCompletedUseCase_GetLessonsCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(request.GetLessonsCompletedRequest), args[2].(string))
	})
	return _c
}

func (_c *MockLessonsCompletedUseCase_GetLessonsCompleted_Call) Return(_a0 *response.LessonsCompletedResponse, _a1 error) *MockLessonsCompletedUseCase_GetLessonsCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLessonsCompletedUseCase_GetLessonsCompleted_Call) RunAndReturn(run func(context.Context, request.GetLessonsCompletedRequest, string) (*response.LessonsCompletedResponse, error)) *MockLessonsCompletedUseCase_GetLessonsCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLessonsCompletedUseCase creates a new instance of MockLessonsCompletedUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonsCompletedUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonsCompletedUseCase {
	mock := &MockLessonsCompletedUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
