// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	catalog "github.com/memberclass-backend-golang/internal/domain/dto/response/catalog"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogUseCase is an autogenerated mock type for the CatalogUseCase type
type MockCatalogUseCase struct {
	mock.Mock
}

type MockCatalogUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogUseCase) EXPECT() *MockCatalogUseCase_Expecter {
	return &MockCatalogUseCase_Expecter{mock: &_m.Mock}
}

// GetCatalog provides a mock function with given fields: ctx, tenantID
func (_m *MockCatalogUseCase) GetCatalog(ctx context.Context, tenantID string) (*catalog.CatalogResponse, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 *catalog.CatalogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*catalog.CatalogResponse, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.CatalogResponse); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.CatalogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogUseCase_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockCatalogUseCase_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockCatalogUseCase_Expecter) GetCatalog(ctx interface{}, tenantID interface{}) *MockCatalogUseCase_GetCatalog_Call {
	return &MockCatalogUseCase_GetCatalog_Call{Call: _e.mock.On("GetCatalog", ctx, tenantID)}
}

func (_c *MockCatalogUseCase_GetCatalog_Call) Run(run func(ctx context.Context, tenantID string)) *MockCatalogUseCase_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogUseCase_GetCatalog_Call) Return(_a0 *catalog.CatalogResponse, _a1 error) *MockCatalogUseCase_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogUseCase_GetCatalog_Call) RunAndReturn(run func(context.Context, string) (*catalog.CatalogResponse, error)) *MockCatalogUseCase_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function with given fields: ctx, courseID, tenantID, includeChildren
func (_m *MockCatalogUseCase) GetCourse(ctx context.Context, courseID string, tenantID string, includeChildren bool) (*catalog.CourseDetailResponse, error) {
	ret := _m.Called(ctx, courseID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *catalog.CourseDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.CourseDetailResponse, error)); ok {
		return rf(ctx, courseID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.CourseDetailResponse); ok {
		r0 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.CourseDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogUseCase_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type MockCatalogUseCase_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogUseCase_Expecter) GetCourse(ctx interface{}, courseID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogUseCase_GetCourse_Call {
	return &MockCatalogUseCase_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, courseID, tenantID, includeChildren)}
}

func (_c *MockCatalogUseCase_GetCourse_Call) Run(run func(ctx context.Context, courseID string, tenantID string, includeChildren bool)) *MockCatalogUseCase_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogUseCase_GetCourse_Call) Return(_a0 *catalog.CourseDetailResponse, _a1 error) *MockCatalogUseCase_GetCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogUseCase_GetCourse_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.CourseDetailResponse, error)) *MockCatalogUseCase_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetLesson provides a mock function with given fields: ctx, lessonID, tenantID
func (_m *MockCatalogUseCase) GetLesson(ctx context.Context, lessonID string, tenantID string) (*catalog.LessonDetailResponse, error) {
	ret := _m.Called(ctx, lessonID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLesson")
	}

	var r0 *catalog.LessonDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*catalog.LessonDetailResponse, error)); ok {
		return rf(ctx, lessonID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *catalog.LessonDetailResponse); ok {
		r0 = rf(ctx, lessonID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.LessonDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lessonID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogUseCase_GetLesson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLesson'
type MockCatalogUseCase_GetLesson_Call struct {
	*mock.Call
}

// GetLesson is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - tenantID string
func (_e *MockCatalogUseCase_Expecter) GetLesson(ctx interface{}, lessonID interface{}, tenantID interface{}) *MockCatalogUseCase_GetLesson_Call {
	return &MockCatalogUseCase_GetLesson_Call{Call: _e.mock.On("GetLesson", ctx, lessonID, tenantID)}
}

func (_c *MockCatalogUseCase_GetLesson_Call) Run(run func(ctx context.Context, lessonID string, tenantID string)) *MockCatalogUseCase_GetLesson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCatalogUseCase_GetLesson_Call) Return(_a0 *catalog.LessonDetailResponse, _a1 error) *MockCatalogUseCase_GetLesson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogUseCase_GetLesson_Call) RunAndReturn(run func(context.Context, string, string) (*catalog.LessonDetailResponse, error)) *MockCatalogUseCase_GetLesson_Call {
	_c.Call.Return(run)
	return _c
}

// GetModule provides a mock function with given fields: ctx, moduleID, tenantID, includeChildren
func (_m *MockCatalogUseCase) GetModule(ctx context.Context, moduleID string, tenantID string, includeChildren bool) (*catalog.ModuleDetailResponse, error) {
	ret := _m.Called(ctx, moduleID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetModule")
	}

	var r0 *catalog.ModuleDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.ModuleDetailResponse, error)); ok {
		return rf(ctx, moduleID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.ModuleDetailResponse); ok {
		r0 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.ModuleDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogUseCase_GetModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModule'
type MockCatalogUseCase_GetModule_Call struct {
	*mock.Call
}

// GetModule is a helper method to define mock.On call
//   - ctx context.Context
//   - moduleID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogUseCase_Expecter) GetModule(ctx interface{}, moduleID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogUseCase_GetModule_Call {
	return &MockCatalogUseCase_GetModule_Call{Call: _e.mock.On("GetModule", ctx, moduleID, tenantID, includeChildren)}
}

func (_c *MockCatalogUseCase_GetModule_Call) Run(run func(ctx context.Context, moduleID string, tenantID string, includeChildren bool)) *MockCatalogUseCase_GetModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogUseCase_GetModule_Call) Return(_a0 *catalog.ModuleDetailResponse, _a1 error) *MockCatalogUseCase_GetModule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogUseCase_GetModule_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.ModuleDetailResponse, error)) *MockCatalogUseCase_GetModule_Call {
	_c.Call.Return(run)
	return _c
}

// GetVitrine provides a mock function with given fields: ctx, vitrineID, tenantID, includeChildren
func (_m *MockCatalogUseCase) GetVitrine(ctx context.Context, vitrineID string, tenantID string, includeChildren bool) (*catalog.VitrineDetailResponse, error) {
	ret := _m.Called(ctx, vitrineID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrine")
	}

	var r0 *catalog.VitrineDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*catalog.VitrineDetailResponse, error)); ok {
		return rf(ctx, vitrineID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *catalog.VitrineDetailResponse); ok {
		r0 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*catalog.VitrineDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogUseCase_GetVitrine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrine'
type MockCatalogUseCase_GetVitrine_Call struct {
	*mock.Call
}

// GetVitrine is a helper method to define mock.On call
//   - ctx context.Context
//   - vitrineID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockCatalogUseCase_Expecter) GetVitrine(ctx interface{}, vitrineID interface{}, tenantID interface{}, includeChildren interface{}) *MockCatalogUseCase_GetVitrine_Call {
	return &MockCatalogUseCase_GetVitrine_Call{Call: _e.mock.On("GetVitrine", ctx, vitrineID, tenantID, includeChildren)}
}

func (_c *MockCatalogUseCase_GetVitrine_Call) Run(run func(ctx context.Context, vitrineID string, tenantID string, includeChildren bool)) *MockCatalogUseCase_GetVitrine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCatalogUseCase_GetVitrine_Call) Return(_a0 *catalog.VitrineDetailResponse, _a1 error) *MockCatalogUseCase_GetVitrine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogUseCase_GetVitrine_Call) RunAndReturn(run func(context.Context, string, string, bool) (*catalog.VitrineDetailResponse, error)) *MockCatalogUseCase_GetVitrine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogUseCase creates a new instance of MockCatalogUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogUseCase {
	mock := &MockCatalogUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
