// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSessionValidatorUseCase is an autogenerated mock type for the SessionValidatorUseCase type
type MockSessionValidatorUseCase struct {
	mock.Mock
}

type MockSessionValidatorUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionValidatorUseCase) EXPECT() *MockSessionValidatorUseCase_Expecter {
	return &MockSessionValidatorUseCase_Expecter{mock: &_m.Mock}
}

// ValidateUserBelongsToTenant provides a mock function with given fields: userID, tenantID
func (_m *MockSessionValidatorUseCase) ValidateUserBelongsToTenant(userID string, tenantID string) error {
	ret := _m.Called(userID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserBelongsToTenant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserBelongsToTenant'
type MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call struct {
	*mock.Call
}

// ValidateUserBelongsToTenant is a helper method to define mock.On call
//   - userID string
//   - tenantID string
func (_e *MockSessionValidatorUseCase_Expecter) ValidateUserBelongsToTenant(userID interface{}, tenantID interface{}) *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call {
	return &MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call{Call: _e.mock.On("ValidateUserBelongsToTenant", userID, tenantID)}
}

func (_c *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call) Run(run func(userID string, tenantID string)) *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call) Return(_a0 error) *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call) RunAndReturn(run func(string, string) error) *MockSessionValidatorUseCase_ValidateUserBelongsToTenant_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserExists provides a mock function with given fields: userID
func (_m *MockSessionValidatorUseCase) ValidateUserExists(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionValidatorUseCase_ValidateUserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserExists'
type MockSessionValidatorUseCase_ValidateUserExists_Call struct {
	*mock.Call
}

// ValidateUserExists is a helper method to define mock.On call
//   - userID string
func (_e *MockSessionValidatorUseCase_Expecter) ValidateUserExists(userID interface{}) *MockSessionValidatorUseCase_ValidateUserExists_Call {
	return &MockSessionValidatorUseCase_ValidateUserExists_Call{Call: _e.mock.On("ValidateUserExists", userID)}
}

func (_c *MockSessionValidatorUseCase_ValidateUserExists_Call) Run(run func(userID string)) *MockSessionValidatorUseCase_ValidateUserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionValidatorUseCase_ValidateUserExists_Call) Return(_a0 error) *MockSessionValidatorUseCase_ValidateUserExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionValidatorUseCase_ValidateUserExists_Call) RunAndReturn(run func(string) error) *MockSessionValidatorUseCase_ValidateUserExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionValidatorUseCase creates a new instance of MockSessionValidatorUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionValidatorUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionValidatorUseCase {
	mock := &MockSessionValidatorUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
