// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	comments "github.com/memberclass-backend-golang/internal/domain/dto/request/comments"
	comment "github.com/memberclass-backend-golang/internal/domain/ports/comment"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSocialCommentRepository is an autogenerated mock type for the SocialCommentRepository type
type MockSocialCommentRepository struct {
	mock.Mock
}

type MockSocialCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocialCommentRepository) EXPECT() *MockSocialCommentRepository_Expecter {
	return &MockSocialCommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req, tenantID
func (_m *MockSocialCommentRepository) Create(ctx context.Context, req comments.CreateSocialCommentRequest, tenantID string) (string, error) {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, comments.CreateSocialCommentRequest, string) (string, error)); ok {
		return rf(ctx, req, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, comments.CreateSocialCommentRequest, string) string); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, comments.CreateSocialCommentRequest, string) error); ok {
		r1 = rf(ctx, req, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialCommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSocialCommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req comments.CreateSocialCommentRequest
//   - tenantID string
func (_e *MockSocialCommentRepository_Expecter) Create(ctx interface{}, req interface{}, tenantID interface{}) *MockSocialCommentRepository_Create_Call {
	return &MockSocialCommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, req, tenantID)}
}

func (_c *MockSocialCommentRepository_Create_Call) Run(run func(ctx context.Context, req comments.CreateSocialCommentRequest, tenantID string)) *MockSocialCommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(comments.CreateSocialCommentRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSocialCommentRepository_Create_Call) Return(_a0 string, _a1 error) *MockSocialCommentRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialCommentRepository_Create_Call) RunAndReturn(run func(context.Context, comments.CreateSocialCommentRequest, string) (string, error)) *MockSocialCommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, postID
func (_m *MockSocialCommentRepository) FindByID(ctx context.Context, postID string) (*comment.PostInfo, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *comment.PostInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*comment.PostInfo, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *comment.PostInfo); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*comment.PostInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSocialCommentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSocialCommentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockSocialCommentRepository_Expecter) FindByID(ctx interface{}, postID interface{}) *MockSocialCommentRepository_FindByID_Call {
	return &MockSocialCommentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, postID)}
}

func (_c *MockSocialCommentRepository_FindByID_Call) Run(run func(ctx context.Context, postID string)) *MockSocialCommentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSocialCommentRepository_FindByID_Call) Return(_a0 *comment.PostInfo, _a1 error) *MockSocialCommentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSocialCommentRepository_FindByID_Call) RunAndReturn(run func(context.Context, string) (*comment.PostInfo, error)) *MockSocialCommentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, req, tenantID
func (_m *MockSocialCommentRepository) Update(ctx context.Context, req comments.CreateSocialCommentRequest, tenantID string) error {
	ret := _m.Called(ctx, req, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, comments.CreateSocialCommentRequest, string) error); ok {
		r0 = rf(ctx, req, tenantID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSocialCommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSocialCommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - req comments.CreateSocialCommentRequest
//   - tenantID string
func (_e *MockSocialCommentRepository_Expecter) Update(ctx interface{}, req interface{}, tenantID interface{}) *MockSocialCommentRepository_Update_Call {
	return &MockSocialCommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, req, tenantID)}
}

func (_c *MockSocialCommentRepository_Update_Call) Run(run func(ctx context.Context, req comments.CreateSocialCommentRequest, tenantID string)) *MockSocialCommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(comments.CreateSocialCommentRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSocialCommentRepository_Update_Call) Return(_a0 error) *MockSocialCommentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSocialCommentRepository_Update_Call) RunAndReturn(run func(context.Context, comments.CreateSocialCommentRequest, string) error) *MockSocialCommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSocialCommentRepository creates a new instance of MockSocialCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocialCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocialCommentRepository {
	mock := &MockSocialCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
