// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockSSORepository is an autogenerated mock type for the SSORepository type
type MockSSORepository struct {
	mock.Mock
}

type MockSSORepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSORepository) EXPECT() *MockSSORepository_Expecter {
	return &MockSSORepository_Expecter{mock: &_m.Mock}
}

// GetUserDocument provides a mock function with given fields: ctx, userID
func (_m *MockSSORepository) GetUserDocument(ctx context.Context, userID string) (*string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDocument")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSORepository_GetUserDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDocument'
type MockSSORepository_GetUserDocument_Call struct {
	*mock.Call
}

// GetUserDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSSORepository_Expecter) GetUserDocument(ctx interface{}, userID interface{}) *MockSSORepository_GetUserDocument_Call {
	return &MockSSORepository_GetUserDocument_Call{Call: _e.mock.On("GetUserDocument", ctx, userID)}
}

func (_c *MockSSORepository_GetUserDocument_Call) Run(run func(ctx context.Context, userID string)) *MockSSORepository_GetUserDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSSORepository_GetUserDocument_Call) Return(_a0 *string, _a1 error) *MockSSORepository_GetUserDocument_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSORepository_GetUserDocument_Call) RunAndReturn(run func(context.Context, string) (*string, error)) *MockSSORepository_GetUserDocument_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSSOToken provides a mock function with given fields: ctx, userID, tenantID, tokenHash, validUntil
func (_m *MockSSORepository) UpdateSSOToken(ctx context.Context, userID string, tenantID string, tokenHash string, validUntil time.Time) error {
	ret := _m.Called(ctx, userID, tenantID, tokenHash, validUntil)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSSOToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, time.Time) error); ok {
		r0 = rf(ctx, userID, tenantID, tokenHash, validUntil)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSSORepository_UpdateSSOToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSSOToken'
type MockSSORepository_UpdateSSOToken_Call struct {
	*mock.Call
}

// UpdateSSOToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tenantID string
//   - tokenHash string
//   - validUntil time.Time
func (_e *MockSSORepository_Expecter) UpdateSSOToken(ctx interface{}, userID interface{}, tenantID interface{}, tokenHash interface{}, validUntil interface{}) *MockSSORepository_UpdateSSOToken_Call {
	return &MockSSORepository_UpdateSSOToken_Call{Call: _e.mock.On("UpdateSSOToken", ctx, userID, tenantID, tokenHash, validUntil)}
}

func (_c *MockSSORepository_UpdateSSOToken_Call) Run(run func(ctx context.Context, userID string, tenantID string, tokenHash string, validUntil time.Time)) *MockSSORepository_UpdateSSOToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(time.Time))
	})
	return _c
}

func (_c *MockSSORepository_UpdateSSOToken_Call) Return(_a0 error) *MockSSORepository_UpdateSSOToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSSORepository_UpdateSSOToken_Call) RunAndReturn(run func(context.Context, string, string, string, time.Time) error) *MockSSORepository_UpdateSSOToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAndConsumeSSOToken provides a mock function with given fields: ctx, tokenHash, ip
func (_m *MockSSORepository) ValidateAndConsumeSSOToken(ctx context.Context, tokenHash string, ip string) (*response.ValidateSSOTokenResponse, error) {
	ret := _m.Called(ctx, tokenHash, ip)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndConsumeSSOToken")
	}

	var r0 *response.ValidateSSOTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ValidateSSOTokenResponse, error)); ok {
		return rf(ctx, tokenHash, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ValidateSSOTokenResponse); ok {
		r0 = rf(ctx, tokenHash, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ValidateSSOTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, tokenHash, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSORepository_ValidateAndConsumeSSOToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAndConsumeSSOToken'
type MockSSORepository_ValidateAndConsumeSSOToken_Call struct {
	*mock.Call
}

// ValidateAndConsumeSSOToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - ip string
func (_e *MockSSORepository_Expecter) ValidateAndConsumeSSOToken(ctx interface{}, tokenHash interface{}, ip interface{}) *MockSSORepository_ValidateAndConsumeSSOToken_Call {
	return &MockSSORepository_ValidateAndConsumeSSOToken_Call{Call: _e.mock.On("ValidateAndConsumeSSOToken", ctx, tokenHash, ip)}
}

func (_c *MockSSORepository_ValidateAndConsumeSSOToken_Call) Run(run func(ctx context.Context, tokenHash string, ip string)) *MockSSORepository_ValidateAndConsumeSSOToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSSORepository_ValidateAndConsumeSSOToken_Call) Return(_a0 *response.ValidateSSOTokenResponse, _a1 error) *MockSSORepository_ValidateAndConsumeSSOToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSORepository_ValidateAndConsumeSSOToken_Call) RunAndReturn(run func(context.Context, string, string) (*response.ValidateSSOTokenResponse, error)) *MockSSORepository_ValidateAndConsumeSSOToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSSORepository creates a new instance of MockSSORepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSORepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSORepository {
	mock := &MockSSORepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
