// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response/social"
	mock "github.com/stretchr/testify/mock"
)

// MockPostSocialRepository is an autogenerated mock type for the PostSocialRepository type
type MockPostSocialRepository struct {
	mock.Mock
}

type MockPostSocialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostSocialRepository) EXPECT() *MockPostSocialRepository_Expecter {
	return &MockPostSocialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, email, platform, url, tenantID
func (_m *MockPostSocialRepository) Create(ctx context.Context, email string, platform string, url string, tenantID string) (*response.PostSocialResponse, error) {
	ret := _m.Called(ctx, email, platform, url, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *response.PostSocialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*response.PostSocialResponse, error)); ok {
		return rf(ctx, email, platform, url, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *response.PostSocialResponse); ok {
		r0 = rf(ctx, email, platform, url, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PostSocialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, platform, url, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostSocialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostSocialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - platform string
//   - url string
//   - tenantID string
func (_e *MockPostSocialRepository_Expecter) Create(ctx interface{}, email interface{}, platform interface{}, url interface{}, tenantID interface{}) *MockPostSocialRepository_Create_Call {
	return &MockPostSocialRepository_Create_Call{Call: _e.mock.On("Create", ctx, email, platform, url, tenantID)}
}

func (_c *MockPostSocialRepository_Create_Call) Run(run func(ctx context.Context, email string, platform string, url string, tenantID string)) *MockPostSocialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockPostSocialRepository_Create_Call) Return(_a0 *response.PostSocialResponse, _a1 error) *MockPostSocialRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostSocialRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*response.PostSocialResponse, error)) *MockPostSocialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email, tenantID
func (_m *MockPostSocialRepository) FindByEmail(ctx context.Context, email string, tenantID string) ([]*response.PostSocialResponse, error) {
	ret := _m.Called(ctx, email, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 []*response.PostSocialResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*response.PostSocialResponse, error)); ok {
		return rf(ctx, email, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*response.PostSocialResponse); ok {
		r0 = rf(ctx, email, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*response.PostSocialResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostSocialRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockPostSocialRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - tenantID string
func (_e *MockPostSocialRepository_Expecter) FindByEmail(ctx interface{}, email interface{}, tenantID interface{}) *MockPostSocialRepository_FindByEmail_Call {
	return &MockPostSocialRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email, tenantID)}
}

func (_c *MockPostSocialRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string, tenantID string)) *MockPostSocialRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPostSocialRepository_FindByEmail_Call) Return(_a0 []*response.PostSocialResponse, _a1 error) *MockPostSocialRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostSocialRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string, string) ([]*response.PostSocialResponse, error)) *MockPostSocialRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostSocialRepository creates a new instance of MockPostSocialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostSocialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostSocialRepository {
	mock := &MockPostSocialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
