// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	vitrine "github.com/memberclass-backend-golang/internal/domain/dto/response/vitrine"
)

// MockVitrineUseCase is an autogenerated mock type for the VitrineUseCase type
type MockVitrineUseCase struct {
	mock.Mock
}

type MockVitrineUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVitrineUseCase) EXPECT() *MockVitrineUseCase_Expecter {
	return &MockVitrineUseCase_Expecter{mock: &_m.Mock}
}

// GetVitrines provides a mock function with given fields: ctx, tenantID
func (_m *MockVitrineUseCase) GetVitrines(ctx context.Context, tenantID string) (*vitrine.VitrineResponse, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrines")
	}

	var r0 *vitrine.VitrineResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*vitrine.VitrineResponse, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *vitrine.VitrineResponse); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.VitrineResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineUseCase_GetVitrines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrines'
type MockVitrineUseCase_GetVitrines_Call struct {
	*mock.Call
}

// GetVitrines is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockVitrineUseCase_Expecter) GetVitrines(ctx interface{}, tenantID interface{}) *MockVitrineUseCase_GetVitrines_Call {
	return &MockVitrineUseCase_GetVitrines_Call{Call: _e.mock.On("GetVitrines", ctx, tenantID)}
}

func (_c *MockVitrineUseCase_GetVitrines_Call) Run(run func(ctx context.Context, tenantID string)) *MockVitrineUseCase_GetVitrines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVitrineUseCase_GetVitrines_Call) Return(_a0 *vitrine.VitrineResponse, _a1 error) *MockVitrineUseCase_GetVitrines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineUseCase_GetVitrines_Call) RunAndReturn(run func(context.Context, string) (*vitrine.VitrineResponse, error)) *MockVitrineUseCase_GetVitrines_Call {
	_c.Call.Return(run)
	return _c
}

// GetCourse provides a mock function with given fields: ctx, courseID, tenantID, includeChildren
func (_m *MockVitrineUseCase) GetCourse(ctx context.Context, courseID string, tenantID string, includeChildren bool) (*vitrine.CourseDetailResponse, error) {
	ret := _m.Called(ctx, courseID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetCourse")
	}

	var r0 *vitrine.CourseDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.CourseDetailResponse, error)); ok {
		return rf(ctx, courseID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.CourseDetailResponse); ok {
		r0 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.CourseDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, courseID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineUseCase_GetCourse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCourse'
type MockVitrineUseCase_GetCourse_Call struct {
	*mock.Call
}

// GetCourse is a helper method to define mock.On call
//   - ctx context.Context
//   - courseID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineUseCase_Expecter) GetCourse(ctx interface{}, courseID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineUseCase_GetCourse_Call {
	return &MockVitrineUseCase_GetCourse_Call{Call: _e.mock.On("GetCourse", ctx, courseID, tenantID, includeChildren)}
}

func (_c *MockVitrineUseCase_GetCourse_Call) Run(run func(ctx context.Context, courseID string, tenantID string, includeChildren bool)) *MockVitrineUseCase_GetCourse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineUseCase_GetCourse_Call) Return(_a0 *vitrine.CourseDetailResponse, _a1 error) *MockVitrineUseCase_GetCourse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineUseCase_GetCourse_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.CourseDetailResponse, error)) *MockVitrineUseCase_GetCourse_Call {
	_c.Call.Return(run)
	return _c
}

// GetLesson provides a mock function with given fields: ctx, lessonID, tenantID
func (_m *MockVitrineUseCase) GetLesson(ctx context.Context, lessonID string, tenantID string) (*vitrine.LessonDetailResponse, error) {
	ret := _m.Called(ctx, lessonID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLesson")
	}

	var r0 *vitrine.LessonDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*vitrine.LessonDetailResponse, error)); ok {
		return rf(ctx, lessonID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *vitrine.LessonDetailResponse); ok {
		r0 = rf(ctx, lessonID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.LessonDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lessonID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineUseCase_GetLesson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLesson'
type MockVitrineUseCase_GetLesson_Call struct {
	*mock.Call
}

// GetLesson is a helper method to define mock.On call
//   - ctx context.Context
//   - lessonID string
//   - tenantID string
func (_e *MockVitrineUseCase_Expecter) GetLesson(ctx interface{}, lessonID interface{}, tenantID interface{}) *MockVitrineUseCase_GetLesson_Call {
	return &MockVitrineUseCase_GetLesson_Call{Call: _e.mock.On("GetLesson", ctx, lessonID, tenantID)}
}

func (_c *MockVitrineUseCase_GetLesson_Call) Run(run func(ctx context.Context, lessonID string, tenantID string)) *MockVitrineUseCase_GetLesson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVitrineUseCase_GetLesson_Call) Return(_a0 *vitrine.LessonDetailResponse, _a1 error) *MockVitrineUseCase_GetLesson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineUseCase_GetLesson_Call) RunAndReturn(run func(context.Context, string, string) (*vitrine.LessonDetailResponse, error)) *MockVitrineUseCase_GetLesson_Call {
	_c.Call.Return(run)
	return _c
}

// GetModule provides a mock function with given fields: ctx, moduleID, tenantID, includeChildren
func (_m *MockVitrineUseCase) GetModule(ctx context.Context, moduleID string, tenantID string, includeChildren bool) (*vitrine.ModuleDetailResponse, error) {
	ret := _m.Called(ctx, moduleID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetModule")
	}

	var r0 *vitrine.ModuleDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.ModuleDetailResponse, error)); ok {
		return rf(ctx, moduleID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.ModuleDetailResponse); ok {
		r0 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.ModuleDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, moduleID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineUseCase_GetModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetModule'
type MockVitrineUseCase_GetModule_Call struct {
	*mock.Call
}

// GetModule is a helper method to define mock.On call
//   - ctx context.Context
//   - moduleID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineUseCase_Expecter) GetModule(ctx interface{}, moduleID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineUseCase_GetModule_Call {
	return &MockVitrineUseCase_GetModule_Call{Call: _e.mock.On("GetModule", ctx, moduleID, tenantID, includeChildren)}
}

func (_c *MockVitrineUseCase_GetModule_Call) Run(run func(ctx context.Context, moduleID string, tenantID string, includeChildren bool)) *MockVitrineUseCase_GetModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineUseCase_GetModule_Call) Return(_a0 *vitrine.ModuleDetailResponse, _a1 error) *MockVitrineUseCase_GetModule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineUseCase_GetModule_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.ModuleDetailResponse, error)) *MockVitrineUseCase_GetModule_Call {
	_c.Call.Return(run)
	return _c
}

// GetVitrine provides a mock function with given fields: ctx, vitrineID, tenantID, includeChildren
func (_m *MockVitrineUseCase) GetVitrine(ctx context.Context, vitrineID string, tenantID string, includeChildren bool) (*vitrine.VitrineDetailResponse, error) {
	ret := _m.Called(ctx, vitrineID, tenantID, includeChildren)

	if len(ret) == 0 {
		panic("no return value specified for GetVitrine")
	}

	var r0 *vitrine.VitrineDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*vitrine.VitrineDetailResponse, error)); ok {
		return rf(ctx, vitrineID, tenantID, includeChildren)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *vitrine.VitrineDetailResponse); ok {
		r0 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vitrine.VitrineDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, vitrineID, tenantID, includeChildren)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVitrineUseCase_GetVitrine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVitrine'
type MockVitrineUseCase_GetVitrine_Call struct {
	*mock.Call
}

// GetVitrine is a helper method to define mock.On call
//   - ctx context.Context
//   - vitrineID string
//   - tenantID string
//   - includeChildren bool
func (_e *MockVitrineUseCase_Expecter) GetVitrine(ctx interface{}, vitrineID interface{}, tenantID interface{}, includeChildren interface{}) *MockVitrineUseCase_GetVitrine_Call {
	return &MockVitrineUseCase_GetVitrine_Call{Call: _e.mock.On("GetVitrine", ctx, vitrineID, tenantID, includeChildren)}
}

func (_c *MockVitrineUseCase_GetVitrine_Call) Run(run func(ctx context.Context, vitrineID string, tenantID string, includeChildren bool)) *MockVitrineUseCase_GetVitrine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockVitrineUseCase_GetVitrine_Call) Return(_a0 *vitrine.VitrineDetailResponse, _a1 error) *MockVitrineUseCase_GetVitrine_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVitrineUseCase_GetVitrine_Call) RunAndReturn(run func(context.Context, string, string, bool) (*vitrine.VitrineDetailResponse, error)) *MockVitrineUseCase_GetVitrine_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVitrineUseCase creates a new instance of MockVitrineUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVitrineUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVitrineUseCase {
	mock := &MockVitrineUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
