// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	response "github.com/memberclass-backend-golang/internal/domain/dto/response"

	sso "github.com/memberclass-backend-golang/internal/domain/dto/request/sso"
)

// MockSSOUseCase is an autogenerated mock type for the SSOUseCase type
type MockSSOUseCase struct {
	mock.Mock
}

type MockSSOUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSSOUseCase) EXPECT() *MockSSOUseCase_Expecter {
	return &MockSSOUseCase_Expecter{mock: &_m.Mock}
}

// GenerateSSOToken provides a mock function with given fields: ctx, req, externalURL
func (_m *MockSSOUseCase) GenerateSSOToken(ctx context.Context, req sso.GenerateSSOTokenRequest, externalURL string) (*response.GenerateSSOTokenResponse, error) {
	ret := _m.Called(ctx, req, externalURL)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSSOToken")
	}

	var r0 *response.GenerateSSOTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sso.GenerateSSOTokenRequest, string) (*response.GenerateSSOTokenResponse, error)); ok {
		return rf(ctx, req, externalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sso.GenerateSSOTokenRequest, string) *response.GenerateSSOTokenResponse); ok {
		r0 = rf(ctx, req, externalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.GenerateSSOTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sso.GenerateSSOTokenRequest, string) error); ok {
		r1 = rf(ctx, req, externalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSOUseCase_GenerateSSOToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSSOToken'
type MockSSOUseCase_GenerateSSOToken_Call struct {
	*mock.Call
}

// GenerateSSOToken is a helper method to define mock.On call
//   - ctx context.Context
//   - req sso.GenerateSSOTokenRequest
//   - externalURL string
func (_e *MockSSOUseCase_Expecter) GenerateSSOToken(ctx interface{}, req interface{}, externalURL interface{}) *MockSSOUseCase_GenerateSSOToken_Call {
	return &MockSSOUseCase_GenerateSSOToken_Call{Call: _e.mock.On("GenerateSSOToken", ctx, req, externalURL)}
}

func (_c *MockSSOUseCase_GenerateSSOToken_Call) Run(run func(ctx context.Context, req sso.GenerateSSOTokenRequest, externalURL string)) *MockSSOUseCase_GenerateSSOToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sso.GenerateSSOTokenRequest), args[2].(string))
	})
	return _c
}

func (_c *MockSSOUseCase_GenerateSSOToken_Call) Return(_a0 *response.GenerateSSOTokenResponse, _a1 error) *MockSSOUseCase_GenerateSSOToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSOUseCase_GenerateSSOToken_Call) RunAndReturn(run func(context.Context, sso.GenerateSSOTokenRequest, string) (*response.GenerateSSOTokenResponse, error)) *MockSSOUseCase_GenerateSSOToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSSOToken provides a mock function with given fields: ctx, token, ip
func (_m *MockSSOUseCase) ValidateSSOToken(ctx context.Context, token string, ip string) (*response.ValidateSSOTokenResponse, error) {
	ret := _m.Called(ctx, token, ip)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSSOToken")
	}

	var r0 *response.ValidateSSOTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*response.ValidateSSOTokenResponse, error)); ok {
		return rf(ctx, token, ip)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *response.ValidateSSOTokenResponse); ok {
		r0 = rf(ctx, token, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ValidateSSOTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, ip)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSSOUseCase_ValidateSSOToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSSOToken'
type MockSSOUseCase_ValidateSSOToken_Call struct {
	*mock.Call
}

// ValidateSSOToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - ip string
func (_e *MockSSOUseCase_Expecter) ValidateSSOToken(ctx interface{}, token interface{}, ip interface{}) *MockSSOUseCase_ValidateSSOToken_Call {
	return &MockSSOUseCase_ValidateSSOToken_Call{Call: _e.mock.On("ValidateSSOToken", ctx, token, ip)}
}

func (_c *MockSSOUseCase_ValidateSSOToken_Call) Run(run func(ctx context.Context, token string, ip string)) *MockSSOUseCase_ValidateSSOToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSSOUseCase_ValidateSSOToken_Call) Return(_a0 *response.ValidateSSOTokenResponse, _a1 error) *MockSSOUseCase_ValidateSSOToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSSOUseCase_ValidateSSOToken_Call) RunAndReturn(run func(context.Context, string, string) (*response.ValidateSSOTokenResponse, error)) *MockSSOUseCase_ValidateSSOToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSSOUseCase creates a new instance of MockSSOUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSSOUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSSOUseCase {
	mock := &MockSSOUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
