// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github.com/memberclass-backend-golang/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockTenantGetTenantBunnyCredentialsUseCase is an autogenerated mock type for the TenantGetTenantBunnyCredentialsUseCase type
type MockTenantGetTenantBunnyCredentialsUseCase struct {
	mock.Mock
}

type MockTenantGetTenantBunnyCredentialsUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantGetTenantBunnyCredentialsUseCase) EXPECT() *MockTenantGetTenantBunnyCredentialsUseCase_Expecter {
	return &MockTenantGetTenantBunnyCredentialsUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: tenantID
func (_m *MockTenantGetTenantBunnyCredentialsUseCase) Execute(tenantID string) (*dto.TenantBunnyCredentials, error) {
	ret := _m.Called(tenantID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dto.TenantBunnyCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dto.TenantBunnyCredentials, error)); ok {
		return rf(tenantID)
	}
	if rf, ok := ret.Get(0).(func(string) *dto.TenantBunnyCredentials); ok {
		r0 = rf(tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TenantBunnyCredentials)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - tenantID string
func (_e *MockTenantGetTenantBunnyCredentialsUseCase_Expecter) Execute(tenantID interface{}) *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call {
	return &MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call{Call: _e.mock.On("Execute", tenantID)}
}

func (_c *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call) Run(run func(tenantID string)) *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call) Return(_a0 *dto.TenantBunnyCredentials, _a1 error) *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call) RunAndReturn(run func(string) (*dto.TenantBunnyCredentials, error)) *MockTenantGetTenantBunnyCredentialsUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantGetTenantBunnyCredentialsUseCase creates a new instance of MockTenantGetTenantBunnyCredentialsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantGetTenantBunnyCredentialsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantGetTenantBunnyCredentialsUseCase {
	mock := &MockTenantGetTenantBunnyCredentialsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
