// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	dto "github.com/memberclass-backend-golang/internal/domain/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockPdfProcessService is an autogenerated mock type for the PdfProcessService type
type MockPdfProcessService struct {
	mock.Mock
}

type MockPdfProcessService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPdfProcessService) EXPECT() *MockPdfProcessService_Expecter {
	return &MockPdfProcessService_Expecter{mock: &_m.Mock}
}

// AddFile provides a mock function with given fields: token, taskID, pdfURL, server
func (_m *MockPdfProcessService) AddFile(token string, taskID string, pdfURL string, server string) (string, error) {
	ret := _m.Called(token, taskID, pdfURL, server)

	if len(ret) == 0 {
		panic("no return value specified for AddFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (string, error)); ok {
		return rf(token, taskID, pdfURL, server)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) string); ok {
		r0 = rf(token, taskID, pdfURL, server)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(token, taskID, pdfURL, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessService_AddFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFile'
type MockPdfProcessService_AddFile_Call struct {
	*mock.Call
}

// AddFile is a helper method to define mock.On call
//   - token string
//   - taskID string
//   - pdfURL string
//   - server string
func (_e *MockPdfProcessService_Expecter) AddFile(token interface{}, taskID interface{}, pdfURL interface{}, server interface{}) *MockPdfProcessService_AddFile_Call {
	return &MockPdfProcessService_AddFile_Call{Call: _e.mock.On("AddFile", token, taskID, pdfURL, server)}
}

func (_c *MockPdfProcessService_AddFile_Call) Run(run func(token string, taskID string, pdfURL string, server string)) *MockPdfProcessService_AddFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPdfProcessService_AddFile_Call) Return(_a0 string, _a1 error) *MockPdfProcessService_AddFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessService_AddFile_Call) RunAndReturn(run func(string, string, string, string) (string, error)) *MockPdfProcessService_AddFile_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: token
func (_m *MockPdfProcessService) CreateTask(token string) (*dto.TaskResponse, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *dto.TaskResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dto.TaskResponse, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *dto.TaskResponse); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TaskResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessService_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockPdfProcessService_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - token string
func (_e *MockPdfProcessService_Expecter) CreateTask(token interface{}) *MockPdfProcessService_CreateTask_Call {
	return &MockPdfProcessService_CreateTask_Call{Call: _e.mock.On("CreateTask", token)}
}

func (_c *MockPdfProcessService_CreateTask_Call) Run(run func(token string)) *MockPdfProcessService_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPdfProcessService_CreateTask_Call) Return(_a0 *dto.TaskResponse, _a1 error) *MockPdfProcessService_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessService_CreateTask_Call) RunAndReturn(run func(string) (*dto.TaskResponse, error)) *MockPdfProcessService_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DownloadTask provides a mock function with given fields: token, taskID, server
func (_m *MockPdfProcessService) DownloadTask(token string, taskID string, server string) ([]byte, error) {
	ret := _m.Called(token, taskID, server)

	if len(ret) == 0 {
		panic("no return value specified for DownloadTask")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return rf(token, taskID, server)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(token, taskID, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(token, taskID, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessService_DownloadTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadTask'
type MockPdfProcessService_DownloadTask_Call struct {
	*mock.Call
}

// DownloadTask is a helper method to define mock.On call
//   - token string
//   - taskID string
//   - server string
func (_e *MockPdfProcessService_Expecter) DownloadTask(token interface{}, taskID interface{}, server interface{}) *MockPdfProcessService_DownloadTask_Call {
	return &MockPdfProcessService_DownloadTask_Call{Call: _e.mock.On("DownloadTask", token, taskID, server)}
}

func (_c *MockPdfProcessService_DownloadTask_Call) Run(run func(token string, taskID string, server string)) *MockPdfProcessService_DownloadTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPdfProcessService_DownloadTask_Call) Return(_a0 []byte, _a1 error) *MockPdfProcessService_DownloadTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessService_DownloadTask_Call) RunAndReturn(run func(string, string, string) ([]byte, error)) *MockPdfProcessService_DownloadTask_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractImagesFromZip provides a mock function with given fields: zipData
func (_m *MockPdfProcessService) ExtractImagesFromZip(zipData []byte) ([]string, error) {
	ret := _m.Called(zipData)

	if len(ret) == 0 {
		panic("no return value specified for ExtractImagesFromZip")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]string, error)); ok {
		return rf(zipData)
	}
	if rf, ok := ret.Get(0).(func([]byte) []string); ok {
		r0 = rf(zipData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(zipData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessService_ExtractImagesFromZip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractImagesFromZip'
type MockPdfProcessService_ExtractImagesFromZip_Call struct {
	*mock.Call
}

// ExtractImagesFromZip is a helper method to define mock.On call
//   - zipData []byte
func (_e *MockPdfProcessService_Expecter) ExtractImagesFromZip(zipData interface{}) *MockPdfProcessService_ExtractImagesFromZip_Call {
	return &MockPdfProcessService_ExtractImagesFromZip_Call{Call: _e.mock.On("ExtractImagesFromZip", zipData)}
}

func (_c *MockPdfProcessService_ExtractImagesFromZip_Call) Run(run func(zipData []byte)) *MockPdfProcessService_ExtractImagesFromZip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockPdfProcessService_ExtractImagesFromZip_Call) Return(_a0 []string, _a1 error) *MockPdfProcessService_ExtractImagesFromZip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessService_ExtractImagesFromZip_Call) RunAndReturn(run func([]byte) ([]string, error)) *MockPdfProcessService_ExtractImagesFromZip_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with no fields
func (_m *MockPdfProcessService) GetToken() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPdfProcessService_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockPdfProcessService_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockPdfProcessService_Expecter) GetToken() *MockPdfProcessService_GetToken_Call {
	return &MockPdfProcessService_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockPdfProcessService_GetToken_Call) Run(run func()) *MockPdfProcessService_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPdfProcessService_GetToken_Call) Return(_a0 string, _a1 error) *MockPdfProcessService_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPdfProcessService_GetToken_Call) RunAndReturn(run func() (string, error)) *MockPdfProcessService_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessTask provides a mock function with given fields: token, taskID, serverFilename, server
func (_m *MockPdfProcessService) ProcessTask(token string, taskID string, serverFilename string, server string) error {
	ret := _m.Called(token, taskID, serverFilename, server)

	if len(ret) == 0 {
		panic("no return value specified for ProcessTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(token, taskID, serverFilename, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPdfProcessService_ProcessTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessTask'
type MockPdfProcessService_ProcessTask_Call struct {
	*mock.Call
}

// ProcessTask is a helper method to define mock.On call
//   - token string
//   - taskID string
//   - serverFilename string
//   - server string
func (_e *MockPdfProcessService_Expecter) ProcessTask(token interface{}, taskID interface{}, serverFilename interface{}, server interface{}) *MockPdfProcessService_ProcessTask_Call {
	return &MockPdfProcessService_ProcessTask_Call{Call: _e.mock.On("ProcessTask", token, taskID, serverFilename, server)}
}

func (_c *MockPdfProcessService_ProcessTask_Call) Run(run func(token string, taskID string, serverFilename string, server string)) *MockPdfProcessService_ProcessTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockPdfProcessService_ProcessTask_Call) Return(_a0 error) *MockPdfProcessService_ProcessTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPdfProcessService_ProcessTask_Call) RunAndReturn(run func(string, string, string, string) error) *MockPdfProcessService_ProcessTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPdfProcessService creates a new instance of MockPdfProcessService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPdfProcessService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPdfProcessService {
	mock := &MockPdfProcessService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
