// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	entities "github.com/memberclass-backend-golang/internal/domain/entities/tenant"
	mock "github.com/stretchr/testify/mock"
)

// MockApiTokenUseCase is an autogenerated mock type for the ApiTokenUseCase type
type MockApiTokenUseCase struct {
	mock.Mock
}

type MockApiTokenUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApiTokenUseCase) EXPECT() *MockApiTokenUseCase_Expecter {
	return &MockApiTokenUseCase_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: ctx, tenantID
func (_m *MockApiTokenUseCase) GenerateToken(ctx context.Context, tenantID string) (string, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiTokenUseCase_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockApiTokenUseCase_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
func (_e *MockApiTokenUseCase_Expecter) GenerateToken(ctx interface{}, tenantID interface{}) *MockApiTokenUseCase_GenerateToken_Call {
	return &MockApiTokenUseCase_GenerateToken_Call{Call: _e.mock.On("GenerateToken", ctx, tenantID)}
}

func (_c *MockApiTokenUseCase_GenerateToken_Call) Run(run func(ctx context.Context, tenantID string)) *MockApiTokenUseCase_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiTokenUseCase_GenerateToken_Call) Return(_a0 string, _a1 error) *MockApiTokenUseCase_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiTokenUseCase_GenerateToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockApiTokenUseCase_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *MockApiTokenUseCase) ValidateToken(ctx context.Context, token string) (*entities.Tenant, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *entities.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Tenant, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Tenant); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApiTokenUseCase_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockApiTokenUseCase_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockApiTokenUseCase_Expecter) ValidateToken(ctx interface{}, token interface{}) *MockApiTokenUseCase_ValidateToken_Call {
	return &MockApiTokenUseCase_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *MockApiTokenUseCase_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *MockApiTokenUseCase_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockApiTokenUseCase_ValidateToken_Call) Return(_a0 *entities.Tenant, _a1 error) *MockApiTokenUseCase_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApiTokenUseCase_ValidateToken_Call) RunAndReturn(run func(context.Context, string) (*entities.Tenant, error)) *MockApiTokenUseCase_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApiTokenUseCase creates a new instance of MockApiTokenUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApiTokenUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApiTokenUseCase {
	mock := &MockApiTokenUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
