// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	activity "github.com/memberclass-backend-golang/internal/domain/dto/response/user/activity"

	mock "github.com/stretchr/testify/mock"

	responseuser "github.com/memberclass-backend-golang/internal/domain/dto/response/user"

	time "time"
)

// MockUserActivityRepository is an autogenerated mock type for the UserActivityRepository type
type MockUserActivityRepository struct {
	mock.Mock
}

type MockUserActivityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserActivityRepository) EXPECT() *MockUserActivityRepository_Expecter {
	return &MockUserActivityRepository_Expecter{mock: &_m.Mock}
}

// FindActivitiesByEmail provides a mock function with given fields: ctx, email, page, limit
func (_m *MockUserActivityRepository) FindActivitiesByEmail(ctx context.Context, email string, page int, limit int) ([]activity.AccessData, int64, error) {
	ret := _m.Called(ctx, email, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindActivitiesByEmail")
	}

	var r0 []activity.AccessData
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]activity.AccessData, int64, error)); ok {
		return rf(ctx, email, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []activity.AccessData); ok {
		r0 = rf(ctx, email, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]activity.AccessData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int64); ok {
		r1 = rf(ctx, email, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, email, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserActivityRepository_FindActivitiesByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActivitiesByEmail'
type MockUserActivityRepository_FindActivitiesByEmail_Call struct {
	*mock.Call
}

// FindActivitiesByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - page int
//   - limit int
func (_e *MockUserActivityRepository_Expecter) FindActivitiesByEmail(ctx interface{}, email interface{}, page interface{}, limit interface{}) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	return &MockUserActivityRepository_FindActivitiesByEmail_Call{Call: _e.mock.On("FindActivitiesByEmail", ctx, email, page, limit)}
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) Run(run func(ctx context.Context, email string, page int, limit int)) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) Return(_a0 []activity.AccessData, _a1 int64, _a2 error) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserActivityRepository_FindActivitiesByEmail_Call) RunAndReturn(run func(context.Context, string, int, int) ([]activity.AccessData, int64, error)) *MockUserActivityRepository_FindActivitiesByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivitySummaryByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserActivityRepository) GetActivitySummaryByEmail(ctx context.Context, email string) (*responseuser.ActivitySummaryResponse, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetActivitySummaryByEmail")
	}

	var r0 *responseuser.ActivitySummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*responseuser.ActivitySummaryResponse, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *responseuser.ActivitySummaryResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responseuser.ActivitySummaryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserActivityRepository_GetActivitySummaryByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivitySummaryByEmail'
type MockUserActivityRepository_GetActivitySummaryByEmail_Call struct {
	*mock.Call
}

// GetActivitySummaryByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserActivityRepository_Expecter) GetActivitySummaryByEmail(ctx interface{}, email interface{}) *MockUserActivityRepository_GetActivitySummaryByEmail_Call {
	return &MockUserActivityRepository_GetActivitySummaryByEmail_Call{Call: _e.mock.On("GetActivitySummaryByEmail", ctx, email)}
}

func (_c *MockUserActivityRepository_GetActivitySummaryByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserActivityRepository_GetActivitySummaryByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserActivityRepository_GetActivitySummaryByEmail_Call) Return(_a0 *responseuser.ActivitySummaryResponse, _a1 error) *MockUserActivityRepository_GetActivitySummaryByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserActivityRepository_GetActivitySummaryByEmail_Call) RunAndReturn(run func(context.Context, string) (*responseuser.ActivitySummaryResponse, error)) *MockUserActivityRepository_GetActivitySummaryByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithActivity provides a mock function with given fields: ctx, tenantID, startDate, endDate, page, limit
func (_m *MockUserActivityRepository) GetUsersWithActivity(ctx context.Context, tenantID string, startDate time.Time, endDate time.Time, page int, limit int) ([]responseuser.UserActivitySummary, int64, error) {
	ret := _m.Called(ctx, tenantID, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithActivity")
	}

	var r0 []responseuser.UserActivitySummary
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int, int) ([]responseuser.UserActivitySummary, int64, error)); ok {
		return rf(ctx, tenantID, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int, int) []responseuser.UserActivitySummary); ok {
		r0 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responseuser.UserActivitySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, int, int) int64); ok {
		r1 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserActivityRepository_GetUsersWithActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithActivity'
type MockUserActivityRepository_GetUsersWithActivity_Call struct {
	*mock.Call
}

// GetUsersWithActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - startDate time.Time
//   - endDate time.Time
//   - page int
//   - limit int
func (_e *MockUserActivityRepository_Expecter) GetUsersWithActivity(ctx interface{}, tenantID interface{}, startDate interface{}, endDate interface{}, page interface{}, limit interface{}) *MockUserActivityRepository_GetUsersWithActivity_Call {
	return &MockUserActivityRepository_GetUsersWithActivity_Call{Call: _e.mock.On("GetUsersWithActivity", ctx, tenantID, startDate, endDate, page, limit)}
}

func (_c *MockUserActivityRepository_GetUsersWithActivity_Call) Run(run func(ctx context.Context, tenantID string, startDate time.Time, endDate time.Time, page int, limit int)) *MockUserActivityRepository_GetUsersWithActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockUserActivityRepository_GetUsersWithActivity_Call) Return(_a0 []responseuser.UserActivitySummary, _a1 int64, _a2 error) *MockUserActivityRepository_GetUsersWithActivity_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserActivityRepository_GetUsersWithActivity_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time, int, int) ([]responseuser.UserActivitySummary, int64, error)) *MockUserActivityRepository_GetUsersWithActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersWithoutActivity provides a mock function with given fields: ctx, tenantID, startDate, endDate, page, limit
func (_m *MockUserActivityRepository) GetUsersWithoutActivity(ctx context.Context, tenantID string, startDate time.Time, endDate time.Time, page int, limit int) ([]responseuser.UserActivitySummary, int64, error) {
	ret := _m.Called(ctx, tenantID, startDate, endDate, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithoutActivity")
	}

	var r0 []responseuser.UserActivitySummary
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int, int) ([]responseuser.UserActivitySummary, int64, error)); ok {
		return rf(ctx, tenantID, startDate, endDate, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time, int, int) []responseuser.UserActivitySummary); ok {
		r0 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responseuser.UserActivitySummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time, int, int) int64); ok {
		r1 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, time.Time, time.Time, int, int) error); ok {
		r2 = rf(ctx, tenantID, startDate, endDate, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserActivityRepository_GetUsersWithoutActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersWithoutActivity'
type MockUserActivityRepository_GetUsersWithoutActivity_Call struct {
	*mock.Call
}

// GetUsersWithoutActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - startDate time.Time
//   - endDate time.Time
//   - page int
//   - limit int
func (_e *MockUserActivityRepository_Expecter) GetUsersWithoutActivity(ctx interface{}, tenantID interface{}, startDate interface{}, endDate interface{}, page interface{}, limit interface{}) *MockUserActivityRepository_GetUsersWithoutActivity_Call {
	return &MockUserActivityRepository_GetUsersWithoutActivity_Call{Call: _e.mock.On("GetUsersWithoutActivity", ctx, tenantID, startDate, endDate, page, limit)}
}

func (_c *MockUserActivityRepository_GetUsersWithoutActivity_Call) Run(run func(ctx context.Context, tenantID string, startDate time.Time, endDate time.Time, page int, limit int)) *MockUserActivityRepository_GetUsersWithoutActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockUserActivityRepository_GetUsersWithoutActivity_Call) Return(_a0 []responseuser.UserActivitySummary, _a1 int64, _a2 error) *MockUserActivityRepository_GetUsersWithoutActivity_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserActivityRepository_GetUsersWithoutActivity_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time, int, int) ([]responseuser.UserActivitySummary, int64, error)) *MockUserActivityRepository_GetUsersWithoutActivity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserActivityRepository creates a new instance of MockUserActivityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserActivityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserActivityRepository {
	mock := &MockUserActivityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
