// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	request "github.com/memberclass-backend-golang/internal/domain/dto/request/comments"
	dto "github.com/memberclass-backend-golang/internal/domain/dto/response/comment"
	entities "github.com/memberclass-backend-golang/internal/domain/entities/comment"

	mock "github.com/stretchr/testify/mock"
)

// MockCommentRepository is an autogenerated mock type for the CommentRepository type
type MockCommentRepository struct {
	mock.Mock
}

type MockCommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommentRepository) EXPECT() *MockCommentRepository_Expecter {
	return &MockCommentRepository_Expecter{mock: &_m.Mock}
}

// FindAllByTenant provides a mock function with given fields: ctx, tenantID, req
func (_m *MockCommentRepository) FindAllByTenant(ctx context.Context, tenantID string, req *request.GetCommentsRequest) ([]*dto.CommentResponse, int64, error) {
	ret := _m.Called(ctx, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByTenant")
	}

	var r0 []*dto.CommentResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *request.GetCommentsRequest) ([]*dto.CommentResponse, int64, error)); ok {
		return rf(ctx, tenantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *request.GetCommentsRequest) []*dto.CommentResponse); ok {
		r0 = rf(ctx, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.CommentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *request.GetCommentsRequest) int64); ok {
		r1 = rf(ctx, tenantID, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *request.GetCommentsRequest) error); ok {
		r2 = rf(ctx, tenantID, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCommentRepository_FindAllByTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByTenant'
type MockCommentRepository_FindAllByTenant_Call struct {
	*mock.Call
}

// FindAllByTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - req *request.GetCommentsRequest
func (_e *MockCommentRepository_Expecter) FindAllByTenant(ctx interface{}, tenantID interface{}, req interface{}) *MockCommentRepository_FindAllByTenant_Call {
	return &MockCommentRepository_FindAllByTenant_Call{Call: _e.mock.On("FindAllByTenant", ctx, tenantID, req)}
}

func (_c *MockCommentRepository_FindAllByTenant_Call) Run(run func(ctx context.Context, tenantID string, req *request.GetCommentsRequest)) *MockCommentRepository_FindAllByTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*request.GetCommentsRequest))
	})
	return _c
}

func (_c *MockCommentRepository_FindAllByTenant_Call) Return(_a0 []*dto.CommentResponse, _a1 int64, _a2 error) *MockCommentRepository_FindAllByTenant_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCommentRepository_FindAllByTenant_Call) RunAndReturn(run func(context.Context, string, *request.GetCommentsRequest) ([]*dto.CommentResponse, int64, error)) *MockCommentRepository_FindAllByTenant_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndTenant provides a mock function with given fields: ctx, commentID, tenantID
func (_m *MockCommentRepository) FindByIDAndTenant(ctx context.Context, commentID string, tenantID string) (*entities.Comment, error) {
	ret := _m.Called(ctx, commentID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndTenant")
	}

	var r0 *entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*entities.Comment, error)); ok {
		return rf(ctx, commentID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *entities.Comment); ok {
		r0 = rf(ctx, commentID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, commentID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentRepository_FindByIDAndTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndTenant'
type MockCommentRepository_FindByIDAndTenant_Call struct {
	*mock.Call
}

// FindByIDAndTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - tenantID string
func (_e *MockCommentRepository_Expecter) FindByIDAndTenant(ctx interface{}, commentID interface{}, tenantID interface{}) *MockCommentRepository_FindByIDAndTenant_Call {
	return &MockCommentRepository_FindByIDAndTenant_Call{Call: _e.mock.On("FindByIDAndTenant", ctx, commentID, tenantID)}
}

func (_c *MockCommentRepository_FindByIDAndTenant_Call) Run(run func(ctx context.Context, commentID string, tenantID string)) *MockCommentRepository_FindByIDAndTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommentRepository_FindByIDAndTenant_Call) Return(_a0 *entities.Comment, _a1 error) *MockCommentRepository_FindByIDAndTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentRepository_FindByIDAndTenant_Call) RunAndReturn(run func(context.Context, string, string) (*entities.Comment, error)) *MockCommentRepository_FindByIDAndTenant_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDAndTenantWithDetails provides a mock function with given fields: ctx, commentID, tenantID
func (_m *MockCommentRepository) FindByIDAndTenantWithDetails(ctx context.Context, commentID string, tenantID string) (*dto.CommentResponse, error) {
	ret := _m.Called(ctx, commentID, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDAndTenantWithDetails")
	}

	var r0 *dto.CommentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*dto.CommentResponse, error)); ok {
		return rf(ctx, commentID, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *dto.CommentResponse); ok {
		r0 = rf(ctx, commentID, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CommentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, commentID, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentRepository_FindByIDAndTenantWithDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDAndTenantWithDetails'
type MockCommentRepository_FindByIDAndTenantWithDetails_Call struct {
	*mock.Call
}

// FindByIDAndTenantWithDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - tenantID string
func (_e *MockCommentRepository_Expecter) FindByIDAndTenantWithDetails(ctx interface{}, commentID interface{}, tenantID interface{}) *MockCommentRepository_FindByIDAndTenantWithDetails_Call {
	return &MockCommentRepository_FindByIDAndTenantWithDetails_Call{Call: _e.mock.On("FindByIDAndTenantWithDetails", ctx, commentID, tenantID)}
}

func (_c *MockCommentRepository_FindByIDAndTenantWithDetails_Call) Run(run func(ctx context.Context, commentID string, tenantID string)) *MockCommentRepository_FindByIDAndTenantWithDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommentRepository_FindByIDAndTenantWithDetails_Call) Return(_a0 *dto.CommentResponse, _a1 error) *MockCommentRepository_FindByIDAndTenantWithDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentRepository_FindByIDAndTenantWithDetails_Call) RunAndReturn(run func(context.Context, string, string) (*dto.CommentResponse, error)) *MockCommentRepository_FindByIDAndTenantWithDetails_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, commentID, answer, published
func (_m *MockCommentRepository) Update(ctx context.Context, commentID string, answer string, published bool) (*entities.Comment, error) {
	ret := _m.Called(ctx, commentID, answer, published)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) (*entities.Comment, error)); ok {
		return rf(ctx, commentID, answer, published)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) *entities.Comment); ok {
		r0 = rf(ctx, commentID, answer, published)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, bool) error); ok {
		r1 = rf(ctx, commentID, answer, published)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID string
//   - answer string
//   - published bool
func (_e *MockCommentRepository_Expecter) Update(ctx interface{}, commentID interface{}, answer interface{}, published interface{}) *MockCommentRepository_Update_Call {
	return &MockCommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, commentID, answer, published)}
}

func (_c *MockCommentRepository_Update_Call) Run(run func(ctx context.Context, commentID string, answer string, published bool)) *MockCommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockCommentRepository_Update_Call) Return(_a0 *entities.Comment, _a1 error) *MockCommentRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommentRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, bool) (*entities.Comment, error)) *MockCommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommentRepository creates a new instance of MockCommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommentRepository {
	mock := &MockCommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
