// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/memberclass-backend-golang/internal/domain/ports/topic"
	mock "github.com/stretchr/testify/mock"
)

// MockTopicRepository is an autogenerated mock type for the TopicRepository type
type MockTopicRepository struct {
	mock.Mock
}

type MockTopicRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopicRepository) EXPECT() *MockTopicRepository_Expecter {
	return &MockTopicRepository_Expecter{mock: &_m.Mock}
}

// FindByIDWithDeliveries provides a mock function with given fields: ctx, topicID
func (_m *MockTopicRepository) FindByIDWithDeliveries(ctx context.Context, topicID string) (*ports.TopicInfo, error) {
	ret := _m.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDWithDeliveries")
	}

	var r0 *ports.TopicInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.TopicInfo, error)); ok {
		return rf(ctx, topicID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.TopicInfo); ok {
		r0 = rf(ctx, topicID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TopicInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_FindByIDWithDeliveries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDWithDeliveries'
type MockTopicRepository_FindByIDWithDeliveries_Call struct {
	*mock.Call
}

// FindByIDWithDeliveries is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID string
func (_e *MockTopicRepository_Expecter) FindByIDWithDeliveries(ctx interface{}, topicID interface{}) *MockTopicRepository_FindByIDWithDeliveries_Call {
	return &MockTopicRepository_FindByIDWithDeliveries_Call{Call: _e.mock.On("FindByIDWithDeliveries", ctx, topicID)}
}

func (_c *MockTopicRepository_FindByIDWithDeliveries_Call) Run(run func(ctx context.Context, topicID string)) *MockTopicRepository_FindByIDWithDeliveries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTopicRepository_FindByIDWithDeliveries_Call) Return(_a0 *ports.TopicInfo, _a1 error) *MockTopicRepository_FindByIDWithDeliveries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_FindByIDWithDeliveries_Call) RunAndReturn(run func(context.Context, string) (*ports.TopicInfo, error)) *MockTopicRepository_FindByIDWithDeliveries_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopicRepository creates a new instance of MockTopicRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopicRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopicRepository {
	mock := &MockTopicRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
