with-expecter: true
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName | snakecase}}.go"
outpkg: mocks
dir: "internal/mocks"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/memberclass-backend-golang/internal/domain/ports:
    interfaces:
      Logger:
      Cache:
      RateLimiterUpload:
      BunnyService:
      UploadVideoBunnyCdnUseCase:
      TenantGetTenantBunnyCredentialsUseCase:
      TenantRepository:
      PdfProcessorUseCase:
      LessonRepository:
      PdfProcessService:
      Storage:
      CommentRepository:
      CommentUseCase:
      ApiTokenUseCase:
      UserActivityRepository:
      UserActivityUseCase:
      UserPurchaseUseCase:
      UserInformationsUseCase:
      SocialCommentUseCase:
      PostSocialUseCase:
      ActivitySummaryUseCase:
      LessonsCompletedUseCase:
      UserRepository:
      SocialCommentRepository:
      PostSocialRepository:
      TopicRepository:
      StudentReportRepository:
      StudentReportUseCase:
      RateLimiterTenant:
      RateLimiterIP:
      AuthUseCase:
      AILessonUseCase:
      AITenantUseCase:
